#!/usr/bin/env python3
"""Generate SDK clientset facades from the public talon.v1 proto services."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PROTO_DIR = ROOT / "proto/talon/v1"
GO_OUT = ROOT / "sdk/go/talon-client/clientset_gen.go"
JS_OUT = ROOT / "sdk/js/talon-client/src/clientset.ts"
PY_OUT = ROOT / "sdk/python/talon-client/src/talon_client/clientset.py"
JAVA_OUT = (
    ROOT
    / "sdk/java/talon-client/src/main/java/systems/impala/talon/client/TalonClientset.java"
)
V1_PROTO_FILES = [
    "namespaces.proto",
    "resources.proto",
    "sessions.proto",
    "channels.proto",
    "workflows.proto",
    "knowledge.proto",
    "auth.proto",
]

HEADER = "Code generated by scripts/sdk/generate_clientsets.py. DO NOT EDIT."


@dataclass(frozen=True)
class Service:
    name: str
    domain: str
    field: str
    accessor: str
    proto_stem: str


def main() -> None:
    services = parse_services([PROTO_DIR / file for file in V1_PROTO_FILES])
    generate_go(services)
    generate_js(services)
    generate_python(services)
    generate_java(services)


def parse_services(paths: list[Path]) -> list[Service]:
    services: list[Service] = []
    for path in paths:
        source = path.read_text()
        for match in re.finditer(r"^service\s+(\w+Service)\s+\{", source, re.MULTILINE):
            name = match.group(1)
            domain = name.removesuffix("Service")
            field = service_field_name(domain)
            services.append(
                Service(
                    name=name,
                    domain=domain,
                    field=field,
                    accessor=to_pascal_case(field),
                    proto_stem=path.stem,
                )
            )
    if not services:
        raise RuntimeError(f"no services found in {PROTO_DIR}")
    return services


def generate_go(services: list[Service]) -> None:
    lines = [
        f"// {HEADER}",
        "",
        "package talonclient",
        "",
        "import (",
        '\ttalonv1 "github.com/impalasys/talon/sdk/go/talon-client/talon/v1"',
        '\t"google.golang.org/grpc"',
        ")",
        "",
        "type Clientset struct {",
    ]
    for service in services:
        lines.append(f"\t{service.field} talonv1.{service.name}Client")
    lines.append("\tclose func() error")
    lines.extend(["}", ""])
    for service in services:
        lines.extend(
            [
                f"func (c *Clientset) {service.accessor}() talonv1.{service.name}Client {{",
                f"\treturn c.{service.field}",
                "}",
                "",
            ]
        )
    lines.extend(
        [
            "func newClientset(conn grpc.ClientConnInterface, close func() error) *Clientset {",
            "\treturn &Clientset{",
        ]
    )
    for service in services:
        lines.append(f"\t\t{service.field}: talonv1.New{service.name}Client(conn),")
    lines.extend(["\t\tclose: close,", "\t}", "}", ""])
    write(GO_OUT, "\n".join(lines))


def generate_js(services: list[Service]) -> None:
    lines = [
        f"// {HEADER}",
        "",
        'import { createPromiseClient, type PromiseClient, type Transport } from "@connectrpc/connect";',
    ]
    for service in services:
        lines.append(
            f'import {{ {service.name} }} from "./gen/proto/talon/v1/{service.proto_stem}_connect.js";'
        )
    lines.extend(["", "export type TalonClient = {"])
    for service in services:
        lines.append(f"  {service.field}: PromiseClient<typeof {service.name}>;")
    lines.extend(["};", "", "export function createTalonClientset(transport: Transport): TalonClient {", "  return {"])
    for service in services:
        lines.append(f"    {service.field}: createPromiseClient({service.name}, transport),")
    lines.extend(["  };", "}", ""])
    write(JS_OUT, "\n".join(lines))


def generate_python(services: list[Service]) -> None:
    lines = [
        f"# {HEADER}",
        "",
    ]
    for service in services:
        lines.append(
            f"from talon_client.proto.talon.v1 import {service.proto_stem}_pb2_grpc"
        )
    lines.extend(
        [
            "",
            "",
        ]
    )
    lines.extend([
        "class TalonClient:",
        "    def __init__(self, channel):",
    ])
    for service in services:
        lines.append(
            f"        self.{service.field} = {service.proto_stem}_pb2_grpc.{service.name}Stub(channel)"
        )
    lines.append("")
    write(PY_OUT, "\n".join(lines))


def generate_java(services: list[Service]) -> None:
    lines = [
        f"// {HEADER}",
        "",
        "package systems.impala.talon.client;",
        "",
        "import io.grpc.Channel;",
    ]
    for service in services:
        lines.append(f"import talon.v1.{service.name}Grpc;")
    lines.extend(
        [
            "",
            "public final class TalonClientset {",
            "    private final Channel channel;",
        ]
    )
    for service in services:
        lines.append(
            f"    private final {service.name}Grpc.{service.name}BlockingStub {service.field};"
        )
        lines.append(
            f"    private final {service.name}Grpc.{service.name}Stub {service.field}Async;"
        )
        lines.append(
            f"    private final {service.name}Grpc.{service.name}FutureStub {service.field}Future;"
        )
    lines.extend(
        [
            "",
            "    public static TalonClientset create(Channel channel) {",
            "        return new TalonClientset(channel);",
            "    }",
            "",
            "    public TalonClientset(Channel channel) {",
            "        this.channel = channel;",
        ]
    )
    for service in services:
        lines.append(
            f"        this.{service.field} = {service.name}Grpc.newBlockingStub(channel);"
        )
        lines.append(f"        this.{service.field}Async = {service.name}Grpc.newStub(channel);")
        lines.append(
            f"        this.{service.field}Future = {service.name}Grpc.newFutureStub(channel);"
        )
    lines.extend(
        [
            "    }",
            "",
            "    public Channel channel() {",
            "        return channel;",
            "    }",
            "",
        ]
    )
    for service in services:
        java_field = service.field
        java_accessor = service.field
        lines.extend(
            [
                f"    public {service.name}Grpc.{service.name}BlockingStub {java_accessor}() {{",
                f"        return {java_field};",
                "    }",
                "",
                f"    public {service.name}Grpc.{service.name}Stub {java_accessor}Async() {{",
                f"        return {java_field}Async;",
                "    }",
                "",
                f"    public {service.name}Grpc.{service.name}FutureStub {java_accessor}Future() {{",
                f"        return {java_field}Future;",
                "    }",
                "",
            ]
        )
    lines.extend(["}", ""])
    write(JAVA_OUT, "\n".join(lines))


def service_field_name(domain: str) -> str:
    if domain == "Auth":
        return "auth"
    if domain == "Knowledge":
        return "knowledge"
    return pluralize(to_camel_case(domain))


def pluralize(value: str) -> str:
    if value.endswith("y"):
        return value[:-1] + "ies"
    if value.endswith(("s", "x", "ch", "sh")):
        return value + "es"
    return value + "s"


def to_camel_case(value: str) -> str:
    pascal = to_pascal_case(value)
    return pascal[:1].lower() + pascal[1:]


def to_pascal_case(value: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in value.split("_"))


def write(path: Path, source: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source.rstrip() + "\n")


if __name__ == "__main__":
    main()
