// Copyright (C) 2026 Impala Systems, Inc.
// SPDX-License-Identifier: AGPL-3.0-only

fn main() -> std::io::Result<()> {
    // All user-facing resource/data protobufs get serde support so they can
    // be deserialized directly from YAML/JSON without shadow structs.
    // The rename_all = "camelCase" matches the YAML convention (systemPrompt, apiVersion, etc.)
    let serde_default_types = [
        ".talon.resources.AcpRuntime",
        ".talon.resources.A2A",
        ".talon.resources.Agent",
        ".talon.resources.AgentCard",
        ".talon.resources.AgentCardCapabilities",
        ".talon.resources.AgentCardSkill",
        ".talon.resources.AgentRuntime",
        ".talon.resources.AgentSpec",
        ".talon.resources.AgentStatus",
        ".talon.resources.Channel",
        ".talon.resources.ChannelContextPolicy",
        ".talon.resources.ChannelSpec",
        ".talon.resources.ChannelStatus",
        ".talon.resources.ChannelSubscription",
        ".talon.resources.ChannelSubscriptionSpec",
        ".talon.resources.CommonResourceStatus",
        ".talon.resources.Connector",
        ".talon.resources.ConnectorClass",
        ".talon.resources.ConnectorClassAuthSpec",
        ".talon.resources.ConnectorClassRuntimeSpec",
        ".talon.resources.ConnectorClassSpec",
        ".talon.resources.ConnectorClassStatus",
        ".talon.resources.ConnectorMatchEntry",
        ".talon.resources.ConnectorMatchIndex",
        ".talon.resources.ConnectorSpec",
        ".talon.resources.ConnectorStatus",
        ".talon.resources.ConnectorTarget",
        ".talon.resources.Connection",
        ".talon.resources.ConnectionAuth",
        ".talon.resources.ConnectionPoolPolicy",
        ".talon.resources.ConnectionSpec",
        ".talon.resources.ConnectionTransport",
        ".talon.resources.ExternalConnectionRef",
        ".talon.resources.DeploymentPlacement",
        ".talon.resources.Deployment",
        ".talon.resources.DeploymentReplica",
        ".talon.resources.DeploymentReplicaSpec",
        ".talon.resources.DeploymentReplicaStatus",
        ".talon.resources.DeploymentSpec",
        ".talon.resources.DeploymentStatus",
        ".talon.resources.Feature",
        ".talon.resources.InternalConnectionRef",
        ".talon.resources.Knowledge",
        ".talon.resources.KnowledgeSpec",
        ".talon.resources.McpAuthBrokerSpec",
        ".talon.resources.McpServer",
        ".talon.resources.McpServerPolicy",
        ".talon.resources.McpServerSpec",
        ".talon.resources.McpToolPolicy",
        ".talon.resources.Model",
        ".talon.resources.ModelPolicy",
        ".talon.resources.ModelProfile",
        ".talon.resources.Namespace",
        ".talon.resources.NamespaceSelector",
        ".talon.resources.NamespaceSpec",
        ".talon.resources.NamespaceStatus",
        ".talon.resources.OwnerReference",
        ".talon.resources.RawResourceSpec",
        ".talon.resources.RawResourceStatus",
        ".talon.resources.Resource",
        ".talon.resources.ResourceCondition",
        ".talon.resources.ResourceManifest",
        ".talon.resources.ResourceMeta",
        ".talon.resources.ResourceRef",
        ".talon.resources.Sandbox",
        ".talon.resources.SandboxClass",
        ".talon.resources.SandboxClassSpec",
        ".talon.resources.SandboxFilesystemSpec",
        ".talon.resources.SandboxLease",
        ".talon.resources.SandboxLeasePolicySpec",
        ".talon.resources.SandboxNetworkSpec",
        ".talon.resources.SandboxPolicy",
        ".talon.resources.SandboxPolicySpec",
        ".talon.resources.SandboxProcessStatus",
        ".talon.resources.SandboxSpec",
        ".talon.resources.SandboxStatus",
        ".talon.resources.SandboxRuntimeTemplateSpec",
        ".talon.resources.SandboxSetupSpec",
        ".talon.resources.SandboxWorkspaceSpec",
        ".talon.resources.Schedule",
        ".talon.resources.ScheduleEvent",
        ".talon.resources.ScheduleSpec",
        ".talon.resources.ScheduleStatus",
        ".talon.resources.ScheduleTarget",
        ".talon.resources.SessionSpec",
        ".talon.resources.Session",
        ".talon.resources.SessionStatus",
        ".talon.resources.Skill",
        ".talon.resources.SkillSpec",
        ".talon.resources.Template",
        ".talon.resources.TemplateSpec",
        ".talon.resources.ThinkingConfig",
        ".talon.resources.Worker",
        ".talon.resources.WorkerEndpoint",
        ".talon.resources.WorkerSpec",
        ".talon.resources.WorkerStatus",
        ".talon.resources.UsageLimit",
        ".talon.resources.UsageLimitStatus",
        ".talon.resources.UsagePolicy",
        ".talon.resources.UsagePolicySpec",
        ".talon.resources.UsagePolicyStatus",
        ".talon.resources.UsageSelector",
        ".talon.resources.Workflow",
        ".talon.resources.WorkflowSpec",
        ".talon.resources.WorkflowStatus",
        ".talon.resources.WorkflowStep",
        ".talon.resources.WorkflowStepOutputPolicy",
        ".talon.resources.WorkflowStepRetryPolicy",
        ".talon.data.ChannelMessage",
        ".talon.data.ApiKeyGrant",
        ".talon.data.ApiKeyRecord",
        ".talon.data.Document",
        ".talon.data.DocumentRef",
        ".talon.data.DocumentSource",
        ".talon.data.Knowledge",
        ".talon.data.KnowledgeSearchResult",
        ".talon.data.ObjectRef",
        ".talon.data.Session",
        ".talon.data.SessionMessage",
        ".talon.data.SessionMessagePart",
        ".talon.data.SessionSubmission",
        ".talon.data.SessionJournalEntry",
        ".talon.data.SessionJournalEntryPayloadLlmResponse",
        ".talon.data.SessionJournalEntryPayloadToolResult",
        ".talon.data.SessionJournalEntryPayloadCommit",
        ".talon.harness.ChatImageUrl",
        ".talon.harness.ChatImageData",
        ".talon.harness.ChatMessage",
        ".talon.harness.ChatRequest",
        ".talon.harness.ChatResponse",
        ".talon.harness.ChatUsage",
        ".talon.harness.Tool",
        ".talon.harness.ToolCall",
        ".talon.harness.ToolCallDelta",
        ".talon.data.WorkflowRun",
        ".talon.data.WorkflowRunEvent",
        ".talon.data.WorkflowStepRun",
        ".talon.events.WorkflowDispatchEvent",
    ];
    let serde_derive_only_types = [
        ".talon.config.Secret",
        ".talon.config.Secret.Source",
        ".talon.config.SecretRef",
        ".talon.resources.ConnectionRef",
        ".talon.resources.ResourceSpec",
        ".talon.resources.ResourceStatus",
        ".talon.data.SessionJournalEntryPayload",
        ".talon.harness.ChatContentPart",
        ".talon.harness.ChatContentPart.Content",
        ".talon.harness.ChatStreamEvent",
        ".talon.harness.ChatStreamEvent.Event",
    ];

    let mut builder = tonic_build::configure().protoc_arg("--experimental_allow_proto3_optional");
    for t in &serde_default_types {
        builder = builder
            .type_attribute(t, "#[derive(serde::Serialize, serde::Deserialize)]")
            .type_attribute(t, "#[serde(rename_all = \"camelCase\", default)]");
    }
    for t in &serde_derive_only_types {
        builder = builder.type_attribute(t, "#[derive(serde::Serialize, serde::Deserialize)]");
    }
    builder = builder.field_attribute(
        ".talon.resources.AgentSpec.capabilities",
        "#[serde(with = \"crate::control::manifest::capabilities_policy_serde\", default)]",
    );
    builder.compile_protos(
        &[
            "proto/config.proto",
            "proto/resources/common.proto",
            "proto/resources/agents.proto",
            "proto/resources/mcp.proto",
            "proto/resources/knowledge.proto",
            "proto/resources/namespaces.proto",
            "proto/resources/channels.proto",
            "proto/resources/connectors.proto",
            "proto/resources/schedules.proto",
            "proto/resources/workflows.proto",
            "proto/resources/deployments.proto",
            "proto/resources/sandboxes.proto",
            "proto/resources/sessions.proto",
            "proto/resources/skills.proto",
            "proto/resources/usage.proto",
            "proto/resources/workers.proto",
            "proto/resources/resource.proto",
            "proto/harness/llm.proto",
            "proto/data/api_keys.proto",
            "proto/data/data.proto",
            "proto/data/search.proto",
            "proto/data/session_submission.proto",
            "proto/data/session_journal_entry.proto",
            "proto/events.proto",
            "proto/talon/v1/auth.proto",
            "proto/talon/v1/channels.proto",
            "proto/talon/v1/connectors.proto",
            "proto/talon/v1/knowledge.proto",
            "proto/talon/v1/namespaces.proto",
            "proto/talon/v1/resources.proto",
            "proto/talon/v1/search.proto",
            "proto/talon/v1/sessions.proto",
            "proto/talon/v1/workflows.proto",
            "proto/talon/worker/v1/fanout.proto",
        ],
        &[".", "third_party/googleapis/"],
    )?;

    Ok(())
}
