packages:
  - "ui"
  - "docs-site"
  - "packages/*"
  - "sdk/js"
  - "sdk/js/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
