// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/resources/resource.proto

package resources

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ResourceMeta          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ResourceSpec          `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *ResourceStatus        `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_resources_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Resource) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Resource) GetMetadata() *ResourceMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Resource) GetSpec() *ResourceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Resource) GetStatus() *ResourceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ResourceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ResourceMeta          `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ResourceSpec          `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceManifest) Reset() {
	*x = ResourceManifest{}
	mi := &file_proto_resources_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceManifest) ProtoMessage() {}

func (x *ResourceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceManifest.ProtoReflect.Descriptor instead.
func (*ResourceManifest) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceManifest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ResourceManifest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResourceManifest) GetMetadata() *ResourceMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ResourceManifest) GetSpec() *ResourceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RawResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawResourceSpec) Reset() {
	*x = RawResourceSpec{}
	mi := &file_proto_resources_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawResourceSpec) ProtoMessage() {}

func (x *RawResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawResourceSpec.ProtoReflect.Descriptor instead.
func (*RawResourceSpec) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{2}
}

func (x *RawResourceSpec) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type RawResourceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawResourceStatus) Reset() {
	*x = RawResourceStatus{}
	mi := &file_proto_resources_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawResourceStatus) ProtoMessage() {}

func (x *RawResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawResourceStatus.ProtoReflect.Descriptor instead.
func (*RawResourceStatus) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{3}
}

func (x *RawResourceStatus) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type ResourceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ResourceSpec_Agent
	//	*ResourceSpec_Workflow
	//	*ResourceSpec_Schedule
	//	*ResourceSpec_Channel
	//	*ResourceSpec_ChannelSubscription
	//	*ResourceSpec_ConnectorClass
	//	*ResourceSpec_Connector
	//	*ResourceSpec_McpServer
	//	*ResourceSpec_Knowledge
	//	*ResourceSpec_Namespace
	//	*ResourceSpec_Session
	//	*ResourceSpec_Skill
	//	*ResourceSpec_Template
	//	*ResourceSpec_Deployment
	//	*ResourceSpec_DeploymentReplica
	//	*ResourceSpec_SandboxClass
	//	*ResourceSpec_SandboxPolicy
	//	*ResourceSpec_Sandbox
	//	*ResourceSpec_Worker
	//	*ResourceSpec_UsagePolicy
	//	*ResourceSpec_Raw
	Kind          isResourceSpec_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_proto_resources_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceSpec) GetKind() isResourceSpec_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ResourceSpec) GetAgent() *AgentSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *ResourceSpec) GetWorkflow() *WorkflowSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *ResourceSpec) GetSchedule() *ScheduleSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Schedule); ok {
			return x.Schedule
		}
	}
	return nil
}

func (x *ResourceSpec) GetChannel() *ChannelSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

func (x *ResourceSpec) GetChannelSubscription() *ChannelSubscriptionSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_ChannelSubscription); ok {
			return x.ChannelSubscription
		}
	}
	return nil
}

func (x *ResourceSpec) GetConnectorClass() *ConnectorClassSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_ConnectorClass); ok {
			return x.ConnectorClass
		}
	}
	return nil
}

func (x *ResourceSpec) GetConnector() *ConnectorSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Connector); ok {
			return x.Connector
		}
	}
	return nil
}

func (x *ResourceSpec) GetMcpServer() *McpServerSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_McpServer); ok {
			return x.McpServer
		}
	}
	return nil
}

func (x *ResourceSpec) GetKnowledge() *KnowledgeSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Knowledge); ok {
			return x.Knowledge
		}
	}
	return nil
}

func (x *ResourceSpec) GetNamespace() *NamespaceSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Namespace); ok {
			return x.Namespace
		}
	}
	return nil
}

func (x *ResourceSpec) GetSession() *SessionSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ResourceSpec) GetSkill() *SkillSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Skill); ok {
			return x.Skill
		}
	}
	return nil
}

func (x *ResourceSpec) GetTemplate() *TemplateSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Template); ok {
			return x.Template
		}
	}
	return nil
}

func (x *ResourceSpec) GetDeployment() *DeploymentSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Deployment); ok {
			return x.Deployment
		}
	}
	return nil
}

func (x *ResourceSpec) GetDeploymentReplica() *DeploymentReplicaSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_DeploymentReplica); ok {
			return x.DeploymentReplica
		}
	}
	return nil
}

func (x *ResourceSpec) GetSandboxClass() *SandboxClassSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_SandboxClass); ok {
			return x.SandboxClass
		}
	}
	return nil
}

func (x *ResourceSpec) GetSandboxPolicy() *SandboxPolicySpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_SandboxPolicy); ok {
			return x.SandboxPolicy
		}
	}
	return nil
}

func (x *ResourceSpec) GetSandbox() *SandboxSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Sandbox); ok {
			return x.Sandbox
		}
	}
	return nil
}

func (x *ResourceSpec) GetWorker() *WorkerSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Worker); ok {
			return x.Worker
		}
	}
	return nil
}

func (x *ResourceSpec) GetUsagePolicy() *UsagePolicySpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_UsagePolicy); ok {
			return x.UsagePolicy
		}
	}
	return nil
}

func (x *ResourceSpec) GetRaw() *RawResourceSpec {
	if x != nil {
		if x, ok := x.Kind.(*ResourceSpec_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isResourceSpec_Kind interface {
	isResourceSpec_Kind()
}

type ResourceSpec_Agent struct {
	Agent *AgentSpec `protobuf:"bytes,1,opt,name=agent,proto3,oneof"`
}

type ResourceSpec_Workflow struct {
	Workflow *WorkflowSpec `protobuf:"bytes,2,opt,name=workflow,proto3,oneof"`
}

type ResourceSpec_Schedule struct {
	Schedule *ScheduleSpec `protobuf:"bytes,3,opt,name=schedule,proto3,oneof"`
}

type ResourceSpec_Channel struct {
	Channel *ChannelSpec `protobuf:"bytes,4,opt,name=channel,proto3,oneof"`
}

type ResourceSpec_ChannelSubscription struct {
	ChannelSubscription *ChannelSubscriptionSpec `protobuf:"bytes,5,opt,name=channel_subscription,json=channelSubscription,proto3,oneof"`
}

type ResourceSpec_ConnectorClass struct {
	ConnectorClass *ConnectorClassSpec `protobuf:"bytes,12,opt,name=connector_class,json=connectorClass,proto3,oneof"`
}

type ResourceSpec_Connector struct {
	Connector *ConnectorSpec `protobuf:"bytes,13,opt,name=connector,proto3,oneof"`
}

type ResourceSpec_McpServer struct {
	McpServer *McpServerSpec `protobuf:"bytes,6,opt,name=mcp_server,json=mcpServer,proto3,oneof"`
}

type ResourceSpec_Knowledge struct {
	Knowledge *KnowledgeSpec `protobuf:"bytes,8,opt,name=knowledge,proto3,oneof"`
}

type ResourceSpec_Namespace struct {
	Namespace *NamespaceSpec `protobuf:"bytes,9,opt,name=namespace,proto3,oneof"`
}

type ResourceSpec_Session struct {
	Session *SessionSpec `protobuf:"bytes,10,opt,name=session,proto3,oneof"`
}

type ResourceSpec_Skill struct {
	Skill *SkillSpec `protobuf:"bytes,11,opt,name=skill,proto3,oneof"`
}

type ResourceSpec_Template struct {
	Template *TemplateSpec `protobuf:"bytes,20,opt,name=template,proto3,oneof"`
}

type ResourceSpec_Deployment struct {
	Deployment *DeploymentSpec `protobuf:"bytes,21,opt,name=deployment,proto3,oneof"`
}

type ResourceSpec_DeploymentReplica struct {
	DeploymentReplica *DeploymentReplicaSpec `protobuf:"bytes,22,opt,name=deployment_replica,json=deploymentReplica,proto3,oneof"`
}

type ResourceSpec_SandboxClass struct {
	SandboxClass *SandboxClassSpec `protobuf:"bytes,40,opt,name=sandbox_class,json=sandboxClass,proto3,oneof"`
}

type ResourceSpec_SandboxPolicy struct {
	SandboxPolicy *SandboxPolicySpec `protobuf:"bytes,41,opt,name=sandbox_policy,json=sandboxPolicy,proto3,oneof"`
}

type ResourceSpec_Sandbox struct {
	Sandbox *SandboxSpec `protobuf:"bytes,42,opt,name=sandbox,proto3,oneof"`
}

type ResourceSpec_Worker struct {
	Worker *WorkerSpec `protobuf:"bytes,50,opt,name=worker,proto3,oneof"`
}

type ResourceSpec_UsagePolicy struct {
	UsagePolicy *UsagePolicySpec `protobuf:"bytes,60,opt,name=usage_policy,json=usagePolicy,proto3,oneof"`
}

type ResourceSpec_Raw struct {
	Raw *RawResourceSpec `protobuf:"bytes,1000,opt,name=raw,proto3,oneof"`
}

func (*ResourceSpec_Agent) isResourceSpec_Kind() {}

func (*ResourceSpec_Workflow) isResourceSpec_Kind() {}

func (*ResourceSpec_Schedule) isResourceSpec_Kind() {}

func (*ResourceSpec_Channel) isResourceSpec_Kind() {}

func (*ResourceSpec_ChannelSubscription) isResourceSpec_Kind() {}

func (*ResourceSpec_ConnectorClass) isResourceSpec_Kind() {}

func (*ResourceSpec_Connector) isResourceSpec_Kind() {}

func (*ResourceSpec_McpServer) isResourceSpec_Kind() {}

func (*ResourceSpec_Knowledge) isResourceSpec_Kind() {}

func (*ResourceSpec_Namespace) isResourceSpec_Kind() {}

func (*ResourceSpec_Session) isResourceSpec_Kind() {}

func (*ResourceSpec_Skill) isResourceSpec_Kind() {}

func (*ResourceSpec_Template) isResourceSpec_Kind() {}

func (*ResourceSpec_Deployment) isResourceSpec_Kind() {}

func (*ResourceSpec_DeploymentReplica) isResourceSpec_Kind() {}

func (*ResourceSpec_SandboxClass) isResourceSpec_Kind() {}

func (*ResourceSpec_SandboxPolicy) isResourceSpec_Kind() {}

func (*ResourceSpec_Sandbox) isResourceSpec_Kind() {}

func (*ResourceSpec_Worker) isResourceSpec_Kind() {}

func (*ResourceSpec_UsagePolicy) isResourceSpec_Kind() {}

func (*ResourceSpec_Raw) isResourceSpec_Kind() {}

type ResourceStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ResourceStatus_Agent
	//	*ResourceStatus_Workflow
	//	*ResourceStatus_Schedule
	//	*ResourceStatus_Channel
	//	*ResourceStatus_ChannelSubscription
	//	*ResourceStatus_ConnectorClass
	//	*ResourceStatus_Connector
	//	*ResourceStatus_McpServer
	//	*ResourceStatus_Knowledge
	//	*ResourceStatus_Namespace
	//	*ResourceStatus_Session
	//	*ResourceStatus_Skill
	//	*ResourceStatus_Template
	//	*ResourceStatus_Deployment
	//	*ResourceStatus_DeploymentReplica
	//	*ResourceStatus_SandboxClass
	//	*ResourceStatus_SandboxPolicy
	//	*ResourceStatus_Sandbox
	//	*ResourceStatus_Worker
	//	*ResourceStatus_UsagePolicy
	//	*ResourceStatus_Raw
	Kind          isResourceStatus_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceStatus) Reset() {
	*x = ResourceStatus{}
	mi := &file_proto_resources_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceStatus) ProtoMessage() {}

func (x *ResourceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resources_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceStatus.ProtoReflect.Descriptor instead.
func (*ResourceStatus) Descriptor() ([]byte, []int) {
	return file_proto_resources_resource_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceStatus) GetKind() isResourceStatus_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ResourceStatus) GetAgent() *AgentStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Agent); ok {
			return x.Agent
		}
	}
	return nil
}

func (x *ResourceStatus) GetWorkflow() *WorkflowStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Workflow); ok {
			return x.Workflow
		}
	}
	return nil
}

func (x *ResourceStatus) GetSchedule() *ScheduleStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Schedule); ok {
			return x.Schedule
		}
	}
	return nil
}

func (x *ResourceStatus) GetChannel() *ChannelStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

func (x *ResourceStatus) GetChannelSubscription() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_ChannelSubscription); ok {
			return x.ChannelSubscription
		}
	}
	return nil
}

func (x *ResourceStatus) GetConnectorClass() *ConnectorClassStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_ConnectorClass); ok {
			return x.ConnectorClass
		}
	}
	return nil
}

func (x *ResourceStatus) GetConnector() *ConnectorStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Connector); ok {
			return x.Connector
		}
	}
	return nil
}

func (x *ResourceStatus) GetMcpServer() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_McpServer); ok {
			return x.McpServer
		}
	}
	return nil
}

func (x *ResourceStatus) GetKnowledge() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Knowledge); ok {
			return x.Knowledge
		}
	}
	return nil
}

func (x *ResourceStatus) GetNamespace() *NamespaceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Namespace); ok {
			return x.Namespace
		}
	}
	return nil
}

func (x *ResourceStatus) GetSession() *SessionStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *ResourceStatus) GetSkill() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Skill); ok {
			return x.Skill
		}
	}
	return nil
}

func (x *ResourceStatus) GetTemplate() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Template); ok {
			return x.Template
		}
	}
	return nil
}

func (x *ResourceStatus) GetDeployment() *DeploymentStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Deployment); ok {
			return x.Deployment
		}
	}
	return nil
}

func (x *ResourceStatus) GetDeploymentReplica() *DeploymentReplicaStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_DeploymentReplica); ok {
			return x.DeploymentReplica
		}
	}
	return nil
}

func (x *ResourceStatus) GetSandboxClass() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_SandboxClass); ok {
			return x.SandboxClass
		}
	}
	return nil
}

func (x *ResourceStatus) GetSandboxPolicy() *CommonResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_SandboxPolicy); ok {
			return x.SandboxPolicy
		}
	}
	return nil
}

func (x *ResourceStatus) GetSandbox() *SandboxStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Sandbox); ok {
			return x.Sandbox
		}
	}
	return nil
}

func (x *ResourceStatus) GetWorker() *WorkerStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Worker); ok {
			return x.Worker
		}
	}
	return nil
}

func (x *ResourceStatus) GetUsagePolicy() *UsagePolicyStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_UsagePolicy); ok {
			return x.UsagePolicy
		}
	}
	return nil
}

func (x *ResourceStatus) GetRaw() *RawResourceStatus {
	if x != nil {
		if x, ok := x.Kind.(*ResourceStatus_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isResourceStatus_Kind interface {
	isResourceStatus_Kind()
}

type ResourceStatus_Agent struct {
	Agent *AgentStatus `protobuf:"bytes,1,opt,name=agent,proto3,oneof"`
}

type ResourceStatus_Workflow struct {
	Workflow *WorkflowStatus `protobuf:"bytes,2,opt,name=workflow,proto3,oneof"`
}

type ResourceStatus_Schedule struct {
	Schedule *ScheduleStatus `protobuf:"bytes,3,opt,name=schedule,proto3,oneof"`
}

type ResourceStatus_Channel struct {
	Channel *ChannelStatus `protobuf:"bytes,4,opt,name=channel,proto3,oneof"`
}

type ResourceStatus_ChannelSubscription struct {
	ChannelSubscription *CommonResourceStatus `protobuf:"bytes,5,opt,name=channel_subscription,json=channelSubscription,proto3,oneof"`
}

type ResourceStatus_ConnectorClass struct {
	ConnectorClass *ConnectorClassStatus `protobuf:"bytes,12,opt,name=connector_class,json=connectorClass,proto3,oneof"`
}

type ResourceStatus_Connector struct {
	Connector *ConnectorStatus `protobuf:"bytes,13,opt,name=connector,proto3,oneof"`
}

type ResourceStatus_McpServer struct {
	McpServer *CommonResourceStatus `protobuf:"bytes,6,opt,name=mcp_server,json=mcpServer,proto3,oneof"`
}

type ResourceStatus_Knowledge struct {
	Knowledge *CommonResourceStatus `protobuf:"bytes,8,opt,name=knowledge,proto3,oneof"`
}

type ResourceStatus_Namespace struct {
	Namespace *NamespaceStatus `protobuf:"bytes,9,opt,name=namespace,proto3,oneof"`
}

type ResourceStatus_Session struct {
	Session *SessionStatus `protobuf:"bytes,10,opt,name=session,proto3,oneof"`
}

type ResourceStatus_Skill struct {
	Skill *CommonResourceStatus `protobuf:"bytes,11,opt,name=skill,proto3,oneof"`
}

type ResourceStatus_Template struct {
	Template *CommonResourceStatus `protobuf:"bytes,20,opt,name=template,proto3,oneof"`
}

type ResourceStatus_Deployment struct {
	Deployment *DeploymentStatus `protobuf:"bytes,21,opt,name=deployment,proto3,oneof"`
}

type ResourceStatus_DeploymentReplica struct {
	DeploymentReplica *DeploymentReplicaStatus `protobuf:"bytes,22,opt,name=deployment_replica,json=deploymentReplica,proto3,oneof"`
}

type ResourceStatus_SandboxClass struct {
	SandboxClass *CommonResourceStatus `protobuf:"bytes,40,opt,name=sandbox_class,json=sandboxClass,proto3,oneof"`
}

type ResourceStatus_SandboxPolicy struct {
	SandboxPolicy *CommonResourceStatus `protobuf:"bytes,41,opt,name=sandbox_policy,json=sandboxPolicy,proto3,oneof"`
}

type ResourceStatus_Sandbox struct {
	Sandbox *SandboxStatus `protobuf:"bytes,42,opt,name=sandbox,proto3,oneof"`
}

type ResourceStatus_Worker struct {
	Worker *WorkerStatus `protobuf:"bytes,50,opt,name=worker,proto3,oneof"`
}

type ResourceStatus_UsagePolicy struct {
	UsagePolicy *UsagePolicyStatus `protobuf:"bytes,60,opt,name=usage_policy,json=usagePolicy,proto3,oneof"`
}

type ResourceStatus_Raw struct {
	Raw *RawResourceStatus `protobuf:"bytes,1000,opt,name=raw,proto3,oneof"`
}

func (*ResourceStatus_Agent) isResourceStatus_Kind() {}

func (*ResourceStatus_Workflow) isResourceStatus_Kind() {}

func (*ResourceStatus_Schedule) isResourceStatus_Kind() {}

func (*ResourceStatus_Channel) isResourceStatus_Kind() {}

func (*ResourceStatus_ChannelSubscription) isResourceStatus_Kind() {}

func (*ResourceStatus_ConnectorClass) isResourceStatus_Kind() {}

func (*ResourceStatus_Connector) isResourceStatus_Kind() {}

func (*ResourceStatus_McpServer) isResourceStatus_Kind() {}

func (*ResourceStatus_Knowledge) isResourceStatus_Kind() {}

func (*ResourceStatus_Namespace) isResourceStatus_Kind() {}

func (*ResourceStatus_Session) isResourceStatus_Kind() {}

func (*ResourceStatus_Skill) isResourceStatus_Kind() {}

func (*ResourceStatus_Template) isResourceStatus_Kind() {}

func (*ResourceStatus_Deployment) isResourceStatus_Kind() {}

func (*ResourceStatus_DeploymentReplica) isResourceStatus_Kind() {}

func (*ResourceStatus_SandboxClass) isResourceStatus_Kind() {}

func (*ResourceStatus_SandboxPolicy) isResourceStatus_Kind() {}

func (*ResourceStatus_Sandbox) isResourceStatus_Kind() {}

func (*ResourceStatus_Worker) isResourceStatus_Kind() {}

func (*ResourceStatus_UsagePolicy) isResourceStatus_Kind() {}

func (*ResourceStatus_Raw) isResourceStatus_Kind() {}

var File_proto_resources_resource_proto protoreflect.FileDescriptor

const file_proto_resources_resource_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/resources/resource.proto\x12\x0ftalon.resources\x1a\x1cproto/resources/agents.proto\x1a\x1eproto/resources/channels.proto\x1a\x1cproto/resources/common.proto\x1a proto/resources/connectors.proto\x1a!proto/resources/deployments.proto\x1a\x1fproto/resources/knowledge.proto\x1a\x19proto/resources/mcp.proto\x1a proto/resources/namespaces.proto\x1a\x1fproto/resources/sandboxes.proto\x1a\x1fproto/resources/schedules.proto\x1a\x1eproto/resources/sessions.proto\x1a\x1cproto/resources/skills.proto\x1a\x1bproto/resources/usage.proto\x1a\x1dproto/resources/workers.proto\x1a\x1fproto/resources/workflows.proto\"\xe6\x01\n" +
	"\bResource\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x129\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1d.talon.resources.ResourceMetaR\bmetadata\x121\n" +
	"\x04spec\x18\x04 \x01(\v2\x1d.talon.resources.ResourceSpecR\x04spec\x127\n" +
	"\x06status\x18\x05 \x01(\v2\x1f.talon.resources.ResourceStatusR\x06status\"\xb5\x01\n" +
	"\x10ResourceManifest\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x129\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1d.talon.resources.ResourceMetaR\bmetadata\x121\n" +
	"\x04spec\x18\x04 \x01(\v2\x1d.talon.resources.ResourceSpecR\x04spec\"%\n" +
	"\x0fRawResourceSpec\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"'\n" +
	"\x11RawResourceStatus\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"\x95\v\n" +
	"\fResourceSpec\x122\n" +
	"\x05agent\x18\x01 \x01(\v2\x1a.talon.resources.AgentSpecH\x00R\x05agent\x12;\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1d.talon.resources.WorkflowSpecH\x00R\bworkflow\x12;\n" +
	"\bschedule\x18\x03 \x01(\v2\x1d.talon.resources.ScheduleSpecH\x00R\bschedule\x128\n" +
	"\achannel\x18\x04 \x01(\v2\x1c.talon.resources.ChannelSpecH\x00R\achannel\x12]\n" +
	"\x14channel_subscription\x18\x05 \x01(\v2(.talon.resources.ChannelSubscriptionSpecH\x00R\x13channelSubscription\x12N\n" +
	"\x0fconnector_class\x18\f \x01(\v2#.talon.resources.ConnectorClassSpecH\x00R\x0econnectorClass\x12>\n" +
	"\tconnector\x18\r \x01(\v2\x1e.talon.resources.ConnectorSpecH\x00R\tconnector\x12?\n" +
	"\n" +
	"mcp_server\x18\x06 \x01(\v2\x1e.talon.resources.McpServerSpecH\x00R\tmcpServer\x12>\n" +
	"\tknowledge\x18\b \x01(\v2\x1e.talon.resources.KnowledgeSpecH\x00R\tknowledge\x12>\n" +
	"\tnamespace\x18\t \x01(\v2\x1e.talon.resources.NamespaceSpecH\x00R\tnamespace\x128\n" +
	"\asession\x18\n" +
	" \x01(\v2\x1c.talon.resources.SessionSpecH\x00R\asession\x122\n" +
	"\x05skill\x18\v \x01(\v2\x1a.talon.resources.SkillSpecH\x00R\x05skill\x12;\n" +
	"\btemplate\x18\x14 \x01(\v2\x1d.talon.resources.TemplateSpecH\x00R\btemplate\x12A\n" +
	"\n" +
	"deployment\x18\x15 \x01(\v2\x1f.talon.resources.DeploymentSpecH\x00R\n" +
	"deployment\x12W\n" +
	"\x12deployment_replica\x18\x16 \x01(\v2&.talon.resources.DeploymentReplicaSpecH\x00R\x11deploymentReplica\x12H\n" +
	"\rsandbox_class\x18( \x01(\v2!.talon.resources.SandboxClassSpecH\x00R\fsandboxClass\x12K\n" +
	"\x0esandbox_policy\x18) \x01(\v2\".talon.resources.SandboxPolicySpecH\x00R\rsandboxPolicy\x128\n" +
	"\asandbox\x18* \x01(\v2\x1c.talon.resources.SandboxSpecH\x00R\asandbox\x125\n" +
	"\x06worker\x182 \x01(\v2\x1b.talon.resources.WorkerSpecH\x00R\x06worker\x12E\n" +
	"\fusage_policy\x18< \x01(\v2 .talon.resources.UsagePolicySpecH\x00R\vusagePolicy\x125\n" +
	"\x03raw\x18\xe8\a \x01(\v2 .talon.resources.RawResourceSpecH\x00R\x03rawB\x06\n" +
	"\x04kindJ\x04\b\a\x10\bR\x12mcp_server_binding\"\xd8\v\n" +
	"\x0eResourceStatus\x124\n" +
	"\x05agent\x18\x01 \x01(\v2\x1c.talon.resources.AgentStatusH\x00R\x05agent\x12=\n" +
	"\bworkflow\x18\x02 \x01(\v2\x1f.talon.resources.WorkflowStatusH\x00R\bworkflow\x12=\n" +
	"\bschedule\x18\x03 \x01(\v2\x1f.talon.resources.ScheduleStatusH\x00R\bschedule\x12:\n" +
	"\achannel\x18\x04 \x01(\v2\x1e.talon.resources.ChannelStatusH\x00R\achannel\x12Z\n" +
	"\x14channel_subscription\x18\x05 \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\x13channelSubscription\x12P\n" +
	"\x0fconnector_class\x18\f \x01(\v2%.talon.resources.ConnectorClassStatusH\x00R\x0econnectorClass\x12@\n" +
	"\tconnector\x18\r \x01(\v2 .talon.resources.ConnectorStatusH\x00R\tconnector\x12F\n" +
	"\n" +
	"mcp_server\x18\x06 \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\tmcpServer\x12E\n" +
	"\tknowledge\x18\b \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\tknowledge\x12@\n" +
	"\tnamespace\x18\t \x01(\v2 .talon.resources.NamespaceStatusH\x00R\tnamespace\x12:\n" +
	"\asession\x18\n" +
	" \x01(\v2\x1e.talon.resources.SessionStatusH\x00R\asession\x12=\n" +
	"\x05skill\x18\v \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\x05skill\x12C\n" +
	"\btemplate\x18\x14 \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\btemplate\x12C\n" +
	"\n" +
	"deployment\x18\x15 \x01(\v2!.talon.resources.DeploymentStatusH\x00R\n" +
	"deployment\x12Y\n" +
	"\x12deployment_replica\x18\x16 \x01(\v2(.talon.resources.DeploymentReplicaStatusH\x00R\x11deploymentReplica\x12L\n" +
	"\rsandbox_class\x18( \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\fsandboxClass\x12N\n" +
	"\x0esandbox_policy\x18) \x01(\v2%.talon.resources.CommonResourceStatusH\x00R\rsandboxPolicy\x12:\n" +
	"\asandbox\x18* \x01(\v2\x1e.talon.resources.SandboxStatusH\x00R\asandbox\x127\n" +
	"\x06worker\x182 \x01(\v2\x1d.talon.resources.WorkerStatusH\x00R\x06worker\x12G\n" +
	"\fusage_policy\x18< \x01(\v2\".talon.resources.UsagePolicyStatusH\x00R\vusagePolicy\x127\n" +
	"\x03raw\x18\xe8\a \x01(\v2\".talon.resources.RawResourceStatusH\x00R\x03rawB\x06\n" +
	"\x04kindJ\x04\b\a\x10\bR\x12mcp_server_bindingb\x06proto3"

var (
	file_proto_resources_resource_proto_rawDescOnce sync.Once
	file_proto_resources_resource_proto_rawDescData []byte
)

func file_proto_resources_resource_proto_rawDescGZIP() []byte {
	file_proto_resources_resource_proto_rawDescOnce.Do(func() {
		file_proto_resources_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resources_resource_proto_rawDesc), len(file_proto_resources_resource_proto_rawDesc)))
	})
	return file_proto_resources_resource_proto_rawDescData
}

var file_proto_resources_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_resources_resource_proto_goTypes = []any{
	(*Resource)(nil),                // 0: talon.resources.Resource
	(*ResourceManifest)(nil),        // 1: talon.resources.ResourceManifest
	(*RawResourceSpec)(nil),         // 2: talon.resources.RawResourceSpec
	(*RawResourceStatus)(nil),       // 3: talon.resources.RawResourceStatus
	(*ResourceSpec)(nil),            // 4: talon.resources.ResourceSpec
	(*ResourceStatus)(nil),          // 5: talon.resources.ResourceStatus
	(*ResourceMeta)(nil),            // 6: talon.resources.ResourceMeta
	(*AgentSpec)(nil),               // 7: talon.resources.AgentSpec
	(*WorkflowSpec)(nil),            // 8: talon.resources.WorkflowSpec
	(*ScheduleSpec)(nil),            // 9: talon.resources.ScheduleSpec
	(*ChannelSpec)(nil),             // 10: talon.resources.ChannelSpec
	(*ChannelSubscriptionSpec)(nil), // 11: talon.resources.ChannelSubscriptionSpec
	(*ConnectorClassSpec)(nil),      // 12: talon.resources.ConnectorClassSpec
	(*ConnectorSpec)(nil),           // 13: talon.resources.ConnectorSpec
	(*McpServerSpec)(nil),           // 14: talon.resources.McpServerSpec
	(*KnowledgeSpec)(nil),           // 15: talon.resources.KnowledgeSpec
	(*NamespaceSpec)(nil),           // 16: talon.resources.NamespaceSpec
	(*SessionSpec)(nil),             // 17: talon.resources.SessionSpec
	(*SkillSpec)(nil),               // 18: talon.resources.SkillSpec
	(*TemplateSpec)(nil),            // 19: talon.resources.TemplateSpec
	(*DeploymentSpec)(nil),          // 20: talon.resources.DeploymentSpec
	(*DeploymentReplicaSpec)(nil),   // 21: talon.resources.DeploymentReplicaSpec
	(*SandboxClassSpec)(nil),        // 22: talon.resources.SandboxClassSpec
	(*SandboxPolicySpec)(nil),       // 23: talon.resources.SandboxPolicySpec
	(*SandboxSpec)(nil),             // 24: talon.resources.SandboxSpec
	(*WorkerSpec)(nil),              // 25: talon.resources.WorkerSpec
	(*UsagePolicySpec)(nil),         // 26: talon.resources.UsagePolicySpec
	(*AgentStatus)(nil),             // 27: talon.resources.AgentStatus
	(*WorkflowStatus)(nil),          // 28: talon.resources.WorkflowStatus
	(*ScheduleStatus)(nil),          // 29: talon.resources.ScheduleStatus
	(*ChannelStatus)(nil),           // 30: talon.resources.ChannelStatus
	(*CommonResourceStatus)(nil),    // 31: talon.resources.CommonResourceStatus
	(*ConnectorClassStatus)(nil),    // 32: talon.resources.ConnectorClassStatus
	(*ConnectorStatus)(nil),         // 33: talon.resources.ConnectorStatus
	(*NamespaceStatus)(nil),         // 34: talon.resources.NamespaceStatus
	(*SessionStatus)(nil),           // 35: talon.resources.SessionStatus
	(*DeploymentStatus)(nil),        // 36: talon.resources.DeploymentStatus
	(*DeploymentReplicaStatus)(nil), // 37: talon.resources.DeploymentReplicaStatus
	(*SandboxStatus)(nil),           // 38: talon.resources.SandboxStatus
	(*WorkerStatus)(nil),            // 39: talon.resources.WorkerStatus
	(*UsagePolicyStatus)(nil),       // 40: talon.resources.UsagePolicyStatus
}
var file_proto_resources_resource_proto_depIdxs = []int32{
	6,  // 0: talon.resources.Resource.metadata:type_name -> talon.resources.ResourceMeta
	4,  // 1: talon.resources.Resource.spec:type_name -> talon.resources.ResourceSpec
	5,  // 2: talon.resources.Resource.status:type_name -> talon.resources.ResourceStatus
	6,  // 3: talon.resources.ResourceManifest.metadata:type_name -> talon.resources.ResourceMeta
	4,  // 4: talon.resources.ResourceManifest.spec:type_name -> talon.resources.ResourceSpec
	7,  // 5: talon.resources.ResourceSpec.agent:type_name -> talon.resources.AgentSpec
	8,  // 6: talon.resources.ResourceSpec.workflow:type_name -> talon.resources.WorkflowSpec
	9,  // 7: talon.resources.ResourceSpec.schedule:type_name -> talon.resources.ScheduleSpec
	10, // 8: talon.resources.ResourceSpec.channel:type_name -> talon.resources.ChannelSpec
	11, // 9: talon.resources.ResourceSpec.channel_subscription:type_name -> talon.resources.ChannelSubscriptionSpec
	12, // 10: talon.resources.ResourceSpec.connector_class:type_name -> talon.resources.ConnectorClassSpec
	13, // 11: talon.resources.ResourceSpec.connector:type_name -> talon.resources.ConnectorSpec
	14, // 12: talon.resources.ResourceSpec.mcp_server:type_name -> talon.resources.McpServerSpec
	15, // 13: talon.resources.ResourceSpec.knowledge:type_name -> talon.resources.KnowledgeSpec
	16, // 14: talon.resources.ResourceSpec.namespace:type_name -> talon.resources.NamespaceSpec
	17, // 15: talon.resources.ResourceSpec.session:type_name -> talon.resources.SessionSpec
	18, // 16: talon.resources.ResourceSpec.skill:type_name -> talon.resources.SkillSpec
	19, // 17: talon.resources.ResourceSpec.template:type_name -> talon.resources.TemplateSpec
	20, // 18: talon.resources.ResourceSpec.deployment:type_name -> talon.resources.DeploymentSpec
	21, // 19: talon.resources.ResourceSpec.deployment_replica:type_name -> talon.resources.DeploymentReplicaSpec
	22, // 20: talon.resources.ResourceSpec.sandbox_class:type_name -> talon.resources.SandboxClassSpec
	23, // 21: talon.resources.ResourceSpec.sandbox_policy:type_name -> talon.resources.SandboxPolicySpec
	24, // 22: talon.resources.ResourceSpec.sandbox:type_name -> talon.resources.SandboxSpec
	25, // 23: talon.resources.ResourceSpec.worker:type_name -> talon.resources.WorkerSpec
	26, // 24: talon.resources.ResourceSpec.usage_policy:type_name -> talon.resources.UsagePolicySpec
	2,  // 25: talon.resources.ResourceSpec.raw:type_name -> talon.resources.RawResourceSpec
	27, // 26: talon.resources.ResourceStatus.agent:type_name -> talon.resources.AgentStatus
	28, // 27: talon.resources.ResourceStatus.workflow:type_name -> talon.resources.WorkflowStatus
	29, // 28: talon.resources.ResourceStatus.schedule:type_name -> talon.resources.ScheduleStatus
	30, // 29: talon.resources.ResourceStatus.channel:type_name -> talon.resources.ChannelStatus
	31, // 30: talon.resources.ResourceStatus.channel_subscription:type_name -> talon.resources.CommonResourceStatus
	32, // 31: talon.resources.ResourceStatus.connector_class:type_name -> talon.resources.ConnectorClassStatus
	33, // 32: talon.resources.ResourceStatus.connector:type_name -> talon.resources.ConnectorStatus
	31, // 33: talon.resources.ResourceStatus.mcp_server:type_name -> talon.resources.CommonResourceStatus
	31, // 34: talon.resources.ResourceStatus.knowledge:type_name -> talon.resources.CommonResourceStatus
	34, // 35: talon.resources.ResourceStatus.namespace:type_name -> talon.resources.NamespaceStatus
	35, // 36: talon.resources.ResourceStatus.session:type_name -> talon.resources.SessionStatus
	31, // 37: talon.resources.ResourceStatus.skill:type_name -> talon.resources.CommonResourceStatus
	31, // 38: talon.resources.ResourceStatus.template:type_name -> talon.resources.CommonResourceStatus
	36, // 39: talon.resources.ResourceStatus.deployment:type_name -> talon.resources.DeploymentStatus
	37, // 40: talon.resources.ResourceStatus.deployment_replica:type_name -> talon.resources.DeploymentReplicaStatus
	31, // 41: talon.resources.ResourceStatus.sandbox_class:type_name -> talon.resources.CommonResourceStatus
	31, // 42: talon.resources.ResourceStatus.sandbox_policy:type_name -> talon.resources.CommonResourceStatus
	38, // 43: talon.resources.ResourceStatus.sandbox:type_name -> talon.resources.SandboxStatus
	39, // 44: talon.resources.ResourceStatus.worker:type_name -> talon.resources.WorkerStatus
	40, // 45: talon.resources.ResourceStatus.usage_policy:type_name -> talon.resources.UsagePolicyStatus
	3,  // 46: talon.resources.ResourceStatus.raw:type_name -> talon.resources.RawResourceStatus
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_proto_resources_resource_proto_init() }
func file_proto_resources_resource_proto_init() {
	if File_proto_resources_resource_proto != nil {
		return
	}
	file_proto_resources_agents_proto_init()
	file_proto_resources_channels_proto_init()
	file_proto_resources_common_proto_init()
	file_proto_resources_connectors_proto_init()
	file_proto_resources_deployments_proto_init()
	file_proto_resources_knowledge_proto_init()
	file_proto_resources_mcp_proto_init()
	file_proto_resources_namespaces_proto_init()
	file_proto_resources_sandboxes_proto_init()
	file_proto_resources_schedules_proto_init()
	file_proto_resources_sessions_proto_init()
	file_proto_resources_skills_proto_init()
	file_proto_resources_usage_proto_init()
	file_proto_resources_workers_proto_init()
	file_proto_resources_workflows_proto_init()
	file_proto_resources_resource_proto_msgTypes[4].OneofWrappers = []any{
		(*ResourceSpec_Agent)(nil),
		(*ResourceSpec_Workflow)(nil),
		(*ResourceSpec_Schedule)(nil),
		(*ResourceSpec_Channel)(nil),
		(*ResourceSpec_ChannelSubscription)(nil),
		(*ResourceSpec_ConnectorClass)(nil),
		(*ResourceSpec_Connector)(nil),
		(*ResourceSpec_McpServer)(nil),
		(*ResourceSpec_Knowledge)(nil),
		(*ResourceSpec_Namespace)(nil),
		(*ResourceSpec_Session)(nil),
		(*ResourceSpec_Skill)(nil),
		(*ResourceSpec_Template)(nil),
		(*ResourceSpec_Deployment)(nil),
		(*ResourceSpec_DeploymentReplica)(nil),
		(*ResourceSpec_SandboxClass)(nil),
		(*ResourceSpec_SandboxPolicy)(nil),
		(*ResourceSpec_Sandbox)(nil),
		(*ResourceSpec_Worker)(nil),
		(*ResourceSpec_UsagePolicy)(nil),
		(*ResourceSpec_Raw)(nil),
	}
	file_proto_resources_resource_proto_msgTypes[5].OneofWrappers = []any{
		(*ResourceStatus_Agent)(nil),
		(*ResourceStatus_Workflow)(nil),
		(*ResourceStatus_Schedule)(nil),
		(*ResourceStatus_Channel)(nil),
		(*ResourceStatus_ChannelSubscription)(nil),
		(*ResourceStatus_ConnectorClass)(nil),
		(*ResourceStatus_Connector)(nil),
		(*ResourceStatus_McpServer)(nil),
		(*ResourceStatus_Knowledge)(nil),
		(*ResourceStatus_Namespace)(nil),
		(*ResourceStatus_Session)(nil),
		(*ResourceStatus_Skill)(nil),
		(*ResourceStatus_Template)(nil),
		(*ResourceStatus_Deployment)(nil),
		(*ResourceStatus_DeploymentReplica)(nil),
		(*ResourceStatus_SandboxClass)(nil),
		(*ResourceStatus_SandboxPolicy)(nil),
		(*ResourceStatus_Sandbox)(nil),
		(*ResourceStatus_Worker)(nil),
		(*ResourceStatus_UsagePolicy)(nil),
		(*ResourceStatus_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resources_resource_proto_rawDesc), len(file_proto_resources_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_resources_resource_proto_goTypes,
		DependencyIndexes: file_proto_resources_resource_proto_depIdxs,
		MessageInfos:      file_proto_resources_resource_proto_msgTypes,
	}.Build()
	File_proto_resources_resource_proto = out.File
	file_proto_resources_resource_proto_goTypes = nil
	file_proto_resources_resource_proto_depIdxs = nil
}
