# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from talon_client.proto.talon.v1 import connectors_pb2 as proto_dot_talon_dot_v1_dot_connectors__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/talon/v1/connectors_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConnectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestMessageEvent = channel.unary_unary(
                '/talon.v1.ConnectorService/IngestMessageEvent',
                request_serializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEvent.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEventResponse.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/talon.v1.ConnectorService/ReportStatus',
                request_serializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorStatusEvent.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorAckResponse.FromString,
                _registered_method=True)


class ConnectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestMessageEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestMessageEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMessageEvent,
                    request_deserializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEvent.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEventResponse.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorStatusEvent.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorAckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talon.v1.ConnectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('talon.v1.ConnectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConnectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestMessageEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ConnectorService/IngestMessageEvent',
            proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEvent.SerializeToString,
            proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorMessageEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ConnectorService/ReportStatus',
            proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorStatusEvent.SerializeToString,
            proto_dot_talon_dot_v1_dot_connectors__pb2.ConnectorAckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
