# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/talon/v1/connectors.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/talon/v1/connectors.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from talon_client.proto.external import connectors_pb2 as proto_dot_external_dot_connectors__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/talon/v1/connectors.proto\x12\x08talon.v1\x1a\x1fproto/external/connectors.proto2\xda\x01\n\x10\x43onnectorService\x12j\n\x12IngestMessageEvent\x12%.talon.external.ConnectorMessageEvent\x1a-.talon.external.ConnectorMessageEventResponse\x12Z\n\x0cReportStatus\x12$.talon.external.ConnectorStatusEvent\x1a$.talon.external.ConnectorAckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.talon.v1.connectors_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECTORSERVICE']._serialized_start=79
  _globals['_CONNECTORSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
