# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from talon_client.proto.talon.v1 import files_pb2 as proto_dot_talon_dot_v1_dot_files__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/talon/v1/files_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
                '/talon.v1.FileService/CreateFile',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_unary(
                '/talon.v1.FileService/ReadFile',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadFileResponse.FromString,
                _registered_method=True)
        self.UpdateFile = channel.unary_unary(
                '/talon.v1.FileService/UpdateFile',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.UpdateFileRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
                _registered_method=True)
        self.GetFileMetadata = channel.unary_unary(
                '/talon.v1.FileService/GetFileMetadata',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.GetFileMetadataRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/talon.v1.FileService/ListFiles',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/talon.v1.FileService/DeleteFile',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.PromoteArtifact = channel.unary_unary(
                '/talon.v1.FileService/PromoteArtifact',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.PromoteArtifactRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """Read RPCs return signed URLs when the configured object store supports
        them. Inline content is a small-object fallback and is capped by the
        gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """V1 returns a flat catalog page filtered by File metadata. Directory-style
        listing and path indexes are intentionally deferred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.CreateFileRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadFileRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadFileResponse.SerializeToString,
            ),
            'UpdateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateFile,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.UpdateFileRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.SerializeToString,
            ),
            'GetFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileMetadata,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.GetFileMetadataRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ListFilesRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ListFilesResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileResponse.SerializeToString,
            ),
            'PromoteArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteArtifact,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.PromoteArtifactRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talon.v1.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('talon.v1.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/CreateFile',
            proto_dot_talon_dot_v1_dot_files__pb2.CreateFileRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/ReadFile',
            proto_dot_talon_dot_v1_dot_files__pb2.ReadFileRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ReadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/UpdateFile',
            proto_dot_talon_dot_v1_dot_files__pb2.UpdateFileRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/GetFileMetadata',
            proto_dot_talon_dot_v1_dot_files__pb2.GetFileMetadataRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/ListFiles',
            proto_dot_talon_dot_v1_dot_files__pb2.ListFilesRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/DeleteFile',
            proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.FileService/PromoteArtifact',
            proto_dot_talon_dot_v1_dot_files__pb2.PromoteArtifactRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ArtifactServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadArtifact = channel.unary_unary(
                '/talon.v1.ArtifactService/ReadArtifact',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactResponse.FromString,
                _registered_method=True)
        self.GetArtifactMetadata = channel.unary_unary(
                '/talon.v1.ArtifactService/GetArtifactMetadata',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.GetArtifactMetadataRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ArtifactResponse.FromString,
                _registered_method=True)
        self.ListArtifacts = channel.unary_unary(
                '/talon.v1.ArtifactService/ListArtifacts',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsResponse.FromString,
                _registered_method=True)
        self.GrantArtifact = channel.unary_unary(
                '/talon.v1.ArtifactService/GrantArtifact',
                request_serializer=proto_dot_talon_dot_v1_dot_files__pb2.GrantArtifactRequest.SerializeToString,
                response_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ArtifactHandleResponse.FromString,
                _registered_method=True)


class ArtifactServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadArtifact(self, request, context):
        """Artifact creation is handled by the runtime/tooling for an active session.
        This service only exposes handle-based artifact reads, metadata, listing,
        and grant operations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtifactMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListArtifacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GrantArtifact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtifactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadArtifact,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactResponse.SerializeToString,
            ),
            'GetArtifactMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtifactMetadata,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.GetArtifactMetadataRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ArtifactResponse.SerializeToString,
            ),
            'ListArtifacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListArtifacts,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsResponse.SerializeToString,
            ),
            'GrantArtifact': grpc.unary_unary_rpc_method_handler(
                    servicer.GrantArtifact,
                    request_deserializer=proto_dot_talon_dot_v1_dot_files__pb2.GrantArtifactRequest.FromString,
                    response_serializer=proto_dot_talon_dot_v1_dot_files__pb2.ArtifactHandleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talon.v1.ArtifactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('talon.v1.ArtifactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtifactService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ArtifactService/ReadArtifact',
            proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ReadArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtifactMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ArtifactService/GetArtifactMetadata',
            proto_dot_talon_dot_v1_dot_files__pb2.GetArtifactMetadataRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ArtifactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListArtifacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ArtifactService/ListArtifacts',
            proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ListArtifactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GrantArtifact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/talon.v1.ArtifactService/GrantArtifact',
            proto_dot_talon_dot_v1_dot_files__pb2.GrantArtifactRequest.SerializeToString,
            proto_dot_talon_dot_v1_dot_files__pb2.ArtifactHandleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
