apiVersion: talon.impalasys.com/v1
kind: Template
metadata:
  name: default
spec:
  kind: Agent
  metadata:
    name: default
  spec:
    systemPrompt: "You are Talon, an autonomous system executing robust actions."
    modelPolicy:
      profiles:
        - name: default
          model:
            provider: cerebras
            name: gpt-oss-120b
            temperature: 0.0
