#!/usr/bin/env sh
set -eu

: "${TALON_ENVOY_GATEWAY_GRPC_HOST:=127.0.0.1}"
: "${TALON_ENVOY_GATEWAY_GRPC_PORT:=50051}"
: "${TALON_ENVOY_GATEWAY_HTTP_HOST:=127.0.0.1}"
: "${TALON_ENVOY_GATEWAY_HTTP_PORT:=50052}"

sed \
  -e "s|{{TALON_ENVOY_GATEWAY_GRPC_HOST}}|${TALON_ENVOY_GATEWAY_GRPC_HOST}|g" \
  -e "s|{{TALON_ENVOY_GATEWAY_GRPC_PORT}}|${TALON_ENVOY_GATEWAY_GRPC_PORT}|g" \
  -e "s|{{TALON_ENVOY_GATEWAY_HTTP_HOST}}|${TALON_ENVOY_GATEWAY_HTTP_HOST}|g" \
  -e "s|{{TALON_ENVOY_GATEWAY_HTTP_PORT}}|${TALON_ENVOY_GATEWAY_HTTP_PORT}|g" \
  /etc/envoy/envoy.yaml.template > /tmp/envoy.yaml

exec "$@"
