# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/data/routing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/data/routing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from talon_client.proto.resources import common_pb2 as proto_dot_resources_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/data/routing.proto\x12\ntalon.data\x1a\x1cproto/resources/common.proto\"m\n\x16SessionMessageConsumer\x12+\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x1c.talon.resources.ResourceRef\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\ncontinuity\x18\x03 \x01(\t\"\x9e\x01\n\x16\x43hannelMessageConsumer\x12-\n\x07\x63hannel\x18\x01 \x01(\x0b\x32\x1c.talon.resources.ResourceRef\x12+\n\x05\x61gent\x18\x02 \x01(\x0b\x32\x1c.talon.resources.ResourceRef\x12\x12\n\ncontinuity\x18\x03 \x01(\t\x12\x14\n\x0creply_policy\x18\x04 \x01(\t\"\x8b\x01\n\x0fMessageConsumer\x12\x35\n\x07session\x18\x01 \x01(\x0b\x32\".talon.data.SessionMessageConsumerH\x00\x12\x35\n\x07\x63hannel\x18\x02 \x01(\x0b\x32\".talon.data.ChannelMessageConsumerH\x00\x42\n\n\x08\x63onsumerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.data.routing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSIONMESSAGECONSUMER']._serialized_start=70
  _globals['_SESSIONMESSAGECONSUMER']._serialized_end=179
  _globals['_CHANNELMESSAGECONSUMER']._serialized_start=182
  _globals['_CHANNELMESSAGECONSUMER']._serialized_end=340
  _globals['_MESSAGECONSUMER']._serialized_start=343
  _globals['_MESSAGECONSUMER']._serialized_end=482
# @@protoc_insertion_point(module_scope)
