// Code generated by scripts/sdk/generate_clientsets.py. DO NOT EDIT.

import { createPromiseClient, type PromiseClient, type Transport } from "@connectrpc/connect";
import {
  NamespaceService,
  ResourceService,
  SessionService,
  ChannelService,
  WorkflowService,
  KnowledgeService,
  AuthService,
} from "./gen/proto/talon/v1/api_connect.js";

export type TalonClient = {
  namespaces: PromiseClient<typeof NamespaceService>;
  resources: PromiseClient<typeof ResourceService>;
  sessions: PromiseClient<typeof SessionService>;
  channels: PromiseClient<typeof ChannelService>;
  workflows: PromiseClient<typeof WorkflowService>;
  knowledge: PromiseClient<typeof KnowledgeService>;
  auth: PromiseClient<typeof AuthService>;
};

export function createTalonClientset(transport: Transport): TalonClient {
  return {
    namespaces: createPromiseClient(NamespaceService, transport),
    resources: createPromiseClient(ResourceService, transport),
    sessions: createPromiseClient(SessionService, transport),
    channels: createPromiseClient(ChannelService, transport),
    workflows: createPromiseClient(WorkflowService, transport),
    knowledge: createPromiseClient(KnowledgeService, transport),
    auth: createPromiseClient(AuthService, transport),
  };
}
