services:
  cloudflare-dev:
    build:
      cache_from:
        - type=gha,scope=talon-cf-cloudflare-dev
      cache_to:
        - type=gha,mode=max,scope=talon-cf-cloudflare-dev

  gateway:
    build:
      cache_from:
        - type=gha,scope=talon-cf-runtime
        - type=gha,scope=talon-runtime
      cache_to:
        - type=gha,mode=max,scope=talon-cf-runtime

  worker:
    build:
      cache_from:
        - type=gha,scope=talon-cf-runtime
        - type=gha,scope=talon-runtime
      cache_to:
        - type=gha,mode=max,scope=talon-cf-runtime

  e2e-tests:
    build:
      cache_from:
        - type=gha,scope=talon-cf-runtime
        - type=gha,scope=talon-runtime
      cache_to:
        - type=gha,mode=max,scope=talon-cf-runtime
