// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/talon/v1/files.proto

package v1

import (
	data "github.com/impalasys/talon/sdk/go/talon-client/talon/data"
	resources "github.com/impalasys/talon/sdk/go/talon-client/talon/resources"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Uri           string                 `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRef) Reset() {
	*x = FileRef{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRef) ProtoMessage() {}

func (x *FileRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRef.ProtoReflect.Descriptor instead.
func (*FileRef) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{0}
}

func (x *FileRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *FileRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type CreateFileRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Namespace     string                    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Path          string                    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MediaType     string                    `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Purpose       resources.FilePurpose     `protobuf:"varint,4,opt,name=purpose,proto3,enum=talon.resources.FilePurpose" json:"purpose,omitempty"`
	IndexPolicy   resources.FileIndexPolicy `protobuf:"varint,5,opt,name=index_policy,json=indexPolicy,proto3,enum=talon.resources.FileIndexPolicy" json:"index_policy,omitempty"`
	Retention     resources.FileRetention   `protobuf:"varint,6,opt,name=retention,proto3,enum=talon.resources.FileRetention" json:"retention,omitempty"`
	Content       []byte                    `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFileRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *CreateFileRequest) GetPurpose() resources.FilePurpose {
	if x != nil {
		return x.Purpose
	}
	return resources.FilePurpose(0)
}

func (x *CreateFileRequest) GetIndexPolicy() resources.FileIndexPolicy {
	if x != nil {
		return x.IndexPolicy
	}
	return resources.FileIndexPolicy(0)
}

func (x *CreateFileRequest) GetRetention() resources.FileRetention {
	if x != nil {
		return x.Retention
	}
	return resources.FileRetention(0)
}

func (x *CreateFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type PrepareFileUploadRequest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Namespace         string                    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Path              string                    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	MediaType         string                    `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Purpose           resources.FilePurpose     `protobuf:"varint,4,opt,name=purpose,proto3,enum=talon.resources.FilePurpose" json:"purpose,omitempty"`
	IndexPolicy       resources.FileIndexPolicy `protobuf:"varint,5,opt,name=index_policy,json=indexPolicy,proto3,enum=talon.resources.FileIndexPolicy" json:"index_policy,omitempty"`
	Retention         resources.FileRetention   `protobuf:"varint,6,opt,name=retention,proto3,enum=talon.resources.FileRetention" json:"retention,omitempty"`
	File              *FileRef                  `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
	ExpectedSizeBytes uint64                    `protobuf:"varint,8,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	ExpectedSha256    string                    `protobuf:"bytes,9,opt,name=expected_sha256,json=expectedSha256,proto3" json:"expected_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareFileUploadRequest) Reset() {
	*x = PrepareFileUploadRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareFileUploadRequest) ProtoMessage() {}

func (x *PrepareFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareFileUploadRequest.ProtoReflect.Descriptor instead.
func (*PrepareFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareFileUploadRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PrepareFileUploadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PrepareFileUploadRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PrepareFileUploadRequest) GetPurpose() resources.FilePurpose {
	if x != nil {
		return x.Purpose
	}
	return resources.FilePurpose(0)
}

func (x *PrepareFileUploadRequest) GetIndexPolicy() resources.FileIndexPolicy {
	if x != nil {
		return x.IndexPolicy
	}
	return resources.FileIndexPolicy(0)
}

func (x *PrepareFileUploadRequest) GetRetention() resources.FileRetention {
	if x != nil {
		return x.Retention
	}
	return resources.FileRetention(0)
}

func (x *PrepareFileUploadRequest) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PrepareFileUploadRequest) GetExpectedSizeBytes() uint64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

func (x *PrepareFileUploadRequest) GetExpectedSha256() string {
	if x != nil {
		return x.ExpectedSha256
	}
	return ""
}

type PrepareFileUploadResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	File                          *resources.File        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	UploadToken                   string                 `protobuf:"bytes,2,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	SignedUploadUrl               string                 `protobuf:"bytes,3,opt,name=signed_upload_url,json=signedUploadUrl,proto3" json:"signed_upload_url,omitempty"`
	Method                        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequiredHeaders               map[string]string      `protobuf:"bytes,5,rep,name=required_headers,json=requiredHeaders,proto3" json:"required_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SignedUrlExpiresAtUnixSeconds int64                  `protobuf:"varint,6,opt,name=signed_url_expires_at_unix_seconds,json=signedUrlExpiresAtUnixSeconds,proto3" json:"signed_url_expires_at_unix_seconds,omitempty"`
	ObjectKey                     string                 `protobuf:"bytes,7,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PrepareFileUploadResponse) Reset() {
	*x = PrepareFileUploadResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareFileUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareFileUploadResponse) ProtoMessage() {}

func (x *PrepareFileUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareFileUploadResponse.ProtoReflect.Descriptor instead.
func (*PrepareFileUploadResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{3}
}

func (x *PrepareFileUploadResponse) GetFile() *resources.File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *PrepareFileUploadResponse) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

func (x *PrepareFileUploadResponse) GetSignedUploadUrl() string {
	if x != nil {
		return x.SignedUploadUrl
	}
	return ""
}

func (x *PrepareFileUploadResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PrepareFileUploadResponse) GetRequiredHeaders() map[string]string {
	if x != nil {
		return x.RequiredHeaders
	}
	return nil
}

func (x *PrepareFileUploadResponse) GetSignedUrlExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.SignedUrlExpiresAtUnixSeconds
	}
	return 0
}

func (x *PrepareFileUploadResponse) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type CompleteFileUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadToken   string                 `protobuf:"bytes,1,opt,name=upload_token,json=uploadToken,proto3" json:"upload_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFileUploadRequest) Reset() {
	*x = CompleteFileUploadRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFileUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFileUploadRequest) ProtoMessage() {}

func (x *CompleteFileUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFileUploadRequest.ProtoReflect.Descriptor instead.
func (*CompleteFileUploadRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteFileUploadRequest) GetUploadToken() string {
	if x != nil {
		return x.UploadToken
	}
	return ""
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{5}
}

func (x *ReadFileRequest) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

type ReadFileResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	File                          *resources.File        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Content                       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SignedUrl                     string                 `protobuf:"bytes,3,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	SignedUrlExpiresAtUnixSeconds int64                  `protobuf:"varint,4,opt,name=signed_url_expires_at_unix_seconds,json=signedUrlExpiresAtUnixSeconds,proto3" json:"signed_url_expires_at_unix_seconds,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFileResponse) GetFile() *resources.File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadFileResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *ReadFileResponse) GetSignedUrlExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.SignedUrlExpiresAtUnixSeconds
	}
	return 0
}

type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFileRequest) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *UpdateFileRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *UpdateFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileMetadataRequest) Reset() {
	*x = GetFileMetadataRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileMetadataRequest) ProtoMessage() {}

func (x *GetFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileMetadataRequest) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

type ListFilesRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Namespace     string                    `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Prefix        string                    `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Purpose       resources.FilePurpose     `protobuf:"varint,3,opt,name=purpose,proto3,enum=talon.resources.FilePurpose" json:"purpose,omitempty"`
	IndexPolicy   resources.FileIndexPolicy `protobuf:"varint,4,opt,name=index_policy,json=indexPolicy,proto3,enum=talon.resources.FileIndexPolicy" json:"index_policy,omitempty"`
	Limit         uint32                    `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                    `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{9}
}

func (x *ListFilesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListFilesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListFilesRequest) GetPurpose() resources.FilePurpose {
	if x != nil {
		return x.Purpose
	}
	return resources.FilePurpose(0)
}

func (x *ListFilesRequest) GetIndexPolicy() resources.FileIndexPolicy {
	if x != nil {
		return x.IndexPolicy
	}
	return resources.FileIndexPolicy(0)
}

func (x *ListFilesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*resources.File      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{10}
}

func (x *ListFilesResponse) GetFiles() []*resources.File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileRef               `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteFileRequest) GetFile() *FileRef {
	if x != nil {
		return x.File
	}
	return nil
}

type DeleteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileResponse) Reset() {
	*x = DeleteFileResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileResponse) ProtoMessage() {}

func (x *DeleteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileResponse.ProtoReflect.Descriptor instead.
func (*DeleteFileResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteFileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PromoteArtifactRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ArtifactUri   string                    `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	TargetPath    string                    `protobuf:"bytes,2,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	MediaType     string                    `protobuf:"bytes,3,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	Purpose       resources.FilePurpose     `protobuf:"varint,4,opt,name=purpose,proto3,enum=talon.resources.FilePurpose" json:"purpose,omitempty"`
	IndexPolicy   resources.FileIndexPolicy `protobuf:"varint,5,opt,name=index_policy,json=indexPolicy,proto3,enum=talon.resources.FileIndexPolicy" json:"index_policy,omitempty"`
	Retention     resources.FileRetention   `protobuf:"varint,6,opt,name=retention,proto3,enum=talon.resources.FileRetention" json:"retention,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteArtifactRequest) Reset() {
	*x = PromoteArtifactRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteArtifactRequest) ProtoMessage() {}

func (x *PromoteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteArtifactRequest.ProtoReflect.Descriptor instead.
func (*PromoteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{13}
}

func (x *PromoteArtifactRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *PromoteArtifactRequest) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *PromoteArtifactRequest) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PromoteArtifactRequest) GetPurpose() resources.FilePurpose {
	if x != nil {
		return x.Purpose
	}
	return resources.FilePurpose(0)
}

func (x *PromoteArtifactRequest) GetIndexPolicy() resources.FileIndexPolicy {
	if x != nil {
		return x.IndexPolicy
	}
	return resources.FileIndexPolicy(0)
}

func (x *PromoteArtifactRequest) GetRetention() resources.FileRetention {
	if x != nil {
		return x.Retention
	}
	return resources.FileRetention(0)
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *resources.File        `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	FileUri       string                 `protobuf:"bytes,2,opt,name=file_uri,json=fileUri,proto3" json:"file_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{14}
}

func (x *FileResponse) GetFile() *resources.File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileResponse) GetFileUri() string {
	if x != nil {
		return x.FileUri
	}
	return ""
}

type ReadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri   string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArtifactRequest) Reset() {
	*x = ReadArtifactRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactRequest) ProtoMessage() {}

func (x *ReadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactRequest.ProtoReflect.Descriptor instead.
func (*ReadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{15}
}

func (x *ReadArtifactRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

type ReadArtifactResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Artifact                      *data.Artifact         `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Content                       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SignedUrl                     string                 `protobuf:"bytes,3,opt,name=signed_url,json=signedUrl,proto3" json:"signed_url,omitempty"`
	SignedUrlExpiresAtUnixSeconds int64                  `protobuf:"varint,4,opt,name=signed_url_expires_at_unix_seconds,json=signedUrlExpiresAtUnixSeconds,proto3" json:"signed_url_expires_at_unix_seconds,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *ReadArtifactResponse) Reset() {
	*x = ReadArtifactResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactResponse) ProtoMessage() {}

func (x *ReadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactResponse.ProtoReflect.Descriptor instead.
func (*ReadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{16}
}

func (x *ReadArtifactResponse) GetArtifact() *data.Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ReadArtifactResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ReadArtifactResponse) GetSignedUrl() string {
	if x != nil {
		return x.SignedUrl
	}
	return ""
}

func (x *ReadArtifactResponse) GetSignedUrlExpiresAtUnixSeconds() int64 {
	if x != nil {
		return x.SignedUrlExpiresAtUnixSeconds
	}
	return 0
}

type GetArtifactMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri   string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArtifactMetadataRequest) Reset() {
	*x = GetArtifactMetadataRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactMetadataRequest) ProtoMessage() {}

func (x *GetArtifactMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactMetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{17}
}

func (x *GetArtifactMetadataRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

type ListArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Limit         uint32                 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsRequest) Reset() {
	*x = ListArtifactsRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsRequest) ProtoMessage() {}

func (x *ListArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{18}
}

func (x *ListArtifactsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListArtifactsRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *ListArtifactsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListArtifactsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListArtifactsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*data.Artifact       `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArtifactsResponse) Reset() {
	*x = ListArtifactsResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArtifactsResponse) ProtoMessage() {}

func (x *ListArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{19}
}

func (x *ListArtifactsResponse) GetArtifacts() []*data.Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ListArtifactsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GrantArtifactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri     string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	TargetAgent     string                 `protobuf:"bytes,2,opt,name=target_agent,json=targetAgent,proto3" json:"target_agent,omitempty"`
	TargetSessionId string                 `protobuf:"bytes,3,opt,name=target_session_id,json=targetSessionId,proto3" json:"target_session_id,omitempty"`
	Operations      []string               `protobuf:"bytes,4,rep,name=operations,proto3" json:"operations,omitempty"`
	TtlSeconds      int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GrantArtifactRequest) Reset() {
	*x = GrantArtifactRequest{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantArtifactRequest) ProtoMessage() {}

func (x *GrantArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantArtifactRequest.ProtoReflect.Descriptor instead.
func (*GrantArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{20}
}

func (x *GrantArtifactRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *GrantArtifactRequest) GetTargetAgent() string {
	if x != nil {
		return x.TargetAgent
	}
	return ""
}

func (x *GrantArtifactRequest) GetTargetSessionId() string {
	if x != nil {
		return x.TargetSessionId
	}
	return ""
}

func (x *GrantArtifactRequest) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *GrantArtifactRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *data.Artifact         `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,2,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactResponse) Reset() {
	*x = ArtifactResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactResponse) ProtoMessage() {}

func (x *ArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactResponse.ProtoReflect.Descriptor instead.
func (*ArtifactResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{21}
}

func (x *ArtifactResponse) GetArtifact() *data.Artifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ArtifactResponse) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

type ArtifactUriResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactUri   string                 `protobuf:"bytes,1,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUriResponse) Reset() {
	*x = ArtifactUriResponse{}
	mi := &file_proto_talon_v1_files_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUriResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUriResponse) ProtoMessage() {}

func (x *ArtifactUriResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_talon_v1_files_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUriResponse.ProtoReflect.Descriptor instead.
func (*ArtifactUriResponse) Descriptor() ([]byte, []int) {
	return file_proto_talon_v1_files_proto_rawDescGZIP(), []int{22}
}

func (x *ArtifactUriResponse) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

var File_proto_talon_v1_files_proto protoreflect.FileDescriptor

const file_proto_talon_v1_files_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/talon/v1/files.proto\x12\btalon.v1\x1a\x15proto/data/data.proto\x1a\x1bproto/resources/files.proto\"a\n" +
	"\aFileRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03uri\x18\x04 \x01(\tR\x03uri\"\xb9\x02\n" +
	"\x11CreateFileRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x126\n" +
	"\apurpose\x18\x04 \x01(\x0e2\x1c.talon.resources.FilePurposeR\apurpose\x12C\n" +
	"\findex_policy\x18\x05 \x01(\x0e2 .talon.resources.FileIndexPolicyR\vindexPolicy\x12<\n" +
	"\tretention\x18\x06 \x01(\x0e2\x1e.talon.resources.FileRetentionR\tretention\x12\x18\n" +
	"\acontent\x18\a \x01(\fR\acontent\"\xa6\x03\n" +
	"\x18PrepareFileUploadRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x126\n" +
	"\apurpose\x18\x04 \x01(\x0e2\x1c.talon.resources.FilePurposeR\apurpose\x12C\n" +
	"\findex_policy\x18\x05 \x01(\x0e2 .talon.resources.FileIndexPolicyR\vindexPolicy\x12<\n" +
	"\tretention\x18\x06 \x01(\x0e2\x1e.talon.resources.FileRetentionR\tretention\x12%\n" +
	"\x04file\x18\a \x01(\v2\x11.talon.v1.FileRefR\x04file\x12.\n" +
	"\x13expected_size_bytes\x18\b \x01(\x04R\x11expectedSizeBytes\x12'\n" +
	"\x0fexpected_sha256\x18\t \x01(\tR\x0eexpectedSha256\"\xc0\x03\n" +
	"\x19PrepareFileUploadResponse\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.talon.resources.FileR\x04file\x12!\n" +
	"\fupload_token\x18\x02 \x01(\tR\vuploadToken\x12*\n" +
	"\x11signed_upload_url\x18\x03 \x01(\tR\x0fsignedUploadUrl\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12c\n" +
	"\x10required_headers\x18\x05 \x03(\v28.talon.v1.PrepareFileUploadResponse.RequiredHeadersEntryR\x0frequiredHeaders\x12I\n" +
	"\"signed_url_expires_at_unix_seconds\x18\x06 \x01(\x03R\x1dsignedUrlExpiresAtUnixSeconds\x12\x1d\n" +
	"\n" +
	"object_key\x18\a \x01(\tR\tobjectKey\x1aB\n" +
	"\x14RequiredHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x19CompleteFileUploadRequest\x12!\n" +
	"\fupload_token\x18\x01 \x01(\tR\vuploadToken\"8\n" +
	"\x0fReadFileRequest\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.talon.v1.FileRefR\x04file\"\xc1\x01\n" +
	"\x10ReadFileResponse\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.talon.resources.FileR\x04file\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x03 \x01(\tR\tsignedUrl\x12I\n" +
	"\"signed_url_expires_at_unix_seconds\x18\x04 \x01(\x03R\x1dsignedUrlExpiresAtUnixSeconds\"s\n" +
	"\x11UpdateFileRequest\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.talon.v1.FileRefR\x04file\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"?\n" +
	"\x16GetFileMetadataRequest\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.talon.v1.FileRefR\x04file\"\xfa\x01\n" +
	"\x10ListFilesRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x126\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x1c.talon.resources.FilePurposeR\apurpose\x12C\n" +
	"\findex_policy\x18\x04 \x01(\x0e2 .talon.resources.FileIndexPolicyR\vindexPolicy\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"h\n" +
	"\x11ListFilesResponse\x12+\n" +
	"\x05files\x18\x01 \x03(\v2\x15.talon.resources.FileR\x05files\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\":\n" +
	"\x11DeleteFileRequest\x12%\n" +
	"\x04file\x18\x01 \x01(\v2\x11.talon.v1.FileRefR\x04file\".\n" +
	"\x12DeleteFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb6\x02\n" +
	"\x16PromoteArtifactRequest\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\x12\x1f\n" +
	"\vtarget_path\x18\x02 \x01(\tR\n" +
	"targetPath\x12\x1d\n" +
	"\n" +
	"media_type\x18\x03 \x01(\tR\tmediaType\x126\n" +
	"\apurpose\x18\x04 \x01(\x0e2\x1c.talon.resources.FilePurposeR\apurpose\x12C\n" +
	"\findex_policy\x18\x05 \x01(\x0e2 .talon.resources.FileIndexPolicyR\vindexPolicy\x12<\n" +
	"\tretention\x18\x06 \x01(\x0e2\x1e.talon.resources.FileRetentionR\tretention\"T\n" +
	"\fFileResponse\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\x15.talon.resources.FileR\x04file\x12\x19\n" +
	"\bfile_uri\x18\x02 \x01(\tR\afileUri\"8\n" +
	"\x13ReadArtifactRequest\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\"\xcc\x01\n" +
	"\x14ReadArtifactResponse\x120\n" +
	"\bartifact\x18\x01 \x01(\v2\x14.talon.data.ArtifactR\bartifact\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"signed_url\x18\x03 \x01(\tR\tsignedUrl\x12I\n" +
	"\"signed_url_expires_at_unix_seconds\x18\x04 \x01(\x03R\x1dsignedUrlExpiresAtUnixSeconds\"?\n" +
	"\x1aGetArtifactMetadataRequest\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\"\xa4\x01\n" +
	"\x14ListArtifactsRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\rR\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageTokenJ\x04\b\x04\x10\x05\"s\n" +
	"\x15ListArtifactsResponse\x122\n" +
	"\tartifacts\x18\x01 \x03(\v2\x14.talon.data.ArtifactR\tartifacts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xc9\x01\n" +
	"\x14GrantArtifactRequest\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri\x12!\n" +
	"\ftarget_agent\x18\x02 \x01(\tR\vtargetAgent\x12*\n" +
	"\x11target_session_id\x18\x03 \x01(\tR\x0ftargetSessionId\x12\x1e\n" +
	"\n" +
	"operations\x18\x04 \x03(\tR\n" +
	"operations\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\"g\n" +
	"\x10ArtifactResponse\x120\n" +
	"\bartifact\x18\x01 \x01(\v2\x14.talon.data.ArtifactR\bartifact\x12!\n" +
	"\fartifact_uri\x18\x02 \x01(\tR\vartifactUri\"8\n" +
	"\x13ArtifactUriResponse\x12!\n" +
	"\fartifact_uri\x18\x01 \x01(\tR\vartifactUri2\xb0\x05\n" +
	"\vFileService\x12A\n" +
	"\n" +
	"CreateFile\x12\x1b.talon.v1.CreateFileRequest\x1a\x16.talon.v1.FileResponse\x12\\\n" +
	"\x11PrepareFileUpload\x12\".talon.v1.PrepareFileUploadRequest\x1a#.talon.v1.PrepareFileUploadResponse\x12Q\n" +
	"\x12CompleteFileUpload\x12#.talon.v1.CompleteFileUploadRequest\x1a\x16.talon.v1.FileResponse\x12A\n" +
	"\bReadFile\x12\x19.talon.v1.ReadFileRequest\x1a\x1a.talon.v1.ReadFileResponse\x12A\n" +
	"\n" +
	"UpdateFile\x12\x1b.talon.v1.UpdateFileRequest\x1a\x16.talon.v1.FileResponse\x12K\n" +
	"\x0fGetFileMetadata\x12 .talon.v1.GetFileMetadataRequest\x1a\x16.talon.v1.FileResponse\x12D\n" +
	"\tListFiles\x12\x1a.talon.v1.ListFilesRequest\x1a\x1b.talon.v1.ListFilesResponse\x12G\n" +
	"\n" +
	"DeleteFile\x12\x1b.talon.v1.DeleteFileRequest\x1a\x1c.talon.v1.DeleteFileResponse\x12K\n" +
	"\x0fPromoteArtifact\x12 .talon.v1.PromoteArtifactRequest\x1a\x16.talon.v1.FileResponse2\xdb\x02\n" +
	"\x0fArtifactService\x12M\n" +
	"\fReadArtifact\x12\x1d.talon.v1.ReadArtifactRequest\x1a\x1e.talon.v1.ReadArtifactResponse\x12W\n" +
	"\x13GetArtifactMetadata\x12$.talon.v1.GetArtifactMetadataRequest\x1a\x1a.talon.v1.ArtifactResponse\x12P\n" +
	"\rListArtifacts\x12\x1e.talon.v1.ListArtifactsRequest\x1a\x1f.talon.v1.ListArtifactsResponse\x12N\n" +
	"\rGrantArtifact\x12\x1e.talon.v1.GrantArtifactRequest\x1a\x1d.talon.v1.ArtifactUriResponseb\x06proto3"

var (
	file_proto_talon_v1_files_proto_rawDescOnce sync.Once
	file_proto_talon_v1_files_proto_rawDescData []byte
)

func file_proto_talon_v1_files_proto_rawDescGZIP() []byte {
	file_proto_talon_v1_files_proto_rawDescOnce.Do(func() {
		file_proto_talon_v1_files_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_talon_v1_files_proto_rawDesc), len(file_proto_talon_v1_files_proto_rawDesc)))
	})
	return file_proto_talon_v1_files_proto_rawDescData
}

var file_proto_talon_v1_files_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_talon_v1_files_proto_goTypes = []any{
	(*FileRef)(nil),                    // 0: talon.v1.FileRef
	(*CreateFileRequest)(nil),          // 1: talon.v1.CreateFileRequest
	(*PrepareFileUploadRequest)(nil),   // 2: talon.v1.PrepareFileUploadRequest
	(*PrepareFileUploadResponse)(nil),  // 3: talon.v1.PrepareFileUploadResponse
	(*CompleteFileUploadRequest)(nil),  // 4: talon.v1.CompleteFileUploadRequest
	(*ReadFileRequest)(nil),            // 5: talon.v1.ReadFileRequest
	(*ReadFileResponse)(nil),           // 6: talon.v1.ReadFileResponse
	(*UpdateFileRequest)(nil),          // 7: talon.v1.UpdateFileRequest
	(*GetFileMetadataRequest)(nil),     // 8: talon.v1.GetFileMetadataRequest
	(*ListFilesRequest)(nil),           // 9: talon.v1.ListFilesRequest
	(*ListFilesResponse)(nil),          // 10: talon.v1.ListFilesResponse
	(*DeleteFileRequest)(nil),          // 11: talon.v1.DeleteFileRequest
	(*DeleteFileResponse)(nil),         // 12: talon.v1.DeleteFileResponse
	(*PromoteArtifactRequest)(nil),     // 13: talon.v1.PromoteArtifactRequest
	(*FileResponse)(nil),               // 14: talon.v1.FileResponse
	(*ReadArtifactRequest)(nil),        // 15: talon.v1.ReadArtifactRequest
	(*ReadArtifactResponse)(nil),       // 16: talon.v1.ReadArtifactResponse
	(*GetArtifactMetadataRequest)(nil), // 17: talon.v1.GetArtifactMetadataRequest
	(*ListArtifactsRequest)(nil),       // 18: talon.v1.ListArtifactsRequest
	(*ListArtifactsResponse)(nil),      // 19: talon.v1.ListArtifactsResponse
	(*GrantArtifactRequest)(nil),       // 20: talon.v1.GrantArtifactRequest
	(*ArtifactResponse)(nil),           // 21: talon.v1.ArtifactResponse
	(*ArtifactUriResponse)(nil),        // 22: talon.v1.ArtifactUriResponse
	nil,                                // 23: talon.v1.PrepareFileUploadResponse.RequiredHeadersEntry
	(resources.FilePurpose)(0),         // 24: talon.resources.FilePurpose
	(resources.FileIndexPolicy)(0),     // 25: talon.resources.FileIndexPolicy
	(resources.FileRetention)(0),       // 26: talon.resources.FileRetention
	(*resources.File)(nil),             // 27: talon.resources.File
	(*data.Artifact)(nil),              // 28: talon.data.Artifact
}
var file_proto_talon_v1_files_proto_depIdxs = []int32{
	24, // 0: talon.v1.CreateFileRequest.purpose:type_name -> talon.resources.FilePurpose
	25, // 1: talon.v1.CreateFileRequest.index_policy:type_name -> talon.resources.FileIndexPolicy
	26, // 2: talon.v1.CreateFileRequest.retention:type_name -> talon.resources.FileRetention
	24, // 3: talon.v1.PrepareFileUploadRequest.purpose:type_name -> talon.resources.FilePurpose
	25, // 4: talon.v1.PrepareFileUploadRequest.index_policy:type_name -> talon.resources.FileIndexPolicy
	26, // 5: talon.v1.PrepareFileUploadRequest.retention:type_name -> talon.resources.FileRetention
	0,  // 6: talon.v1.PrepareFileUploadRequest.file:type_name -> talon.v1.FileRef
	27, // 7: talon.v1.PrepareFileUploadResponse.file:type_name -> talon.resources.File
	23, // 8: talon.v1.PrepareFileUploadResponse.required_headers:type_name -> talon.v1.PrepareFileUploadResponse.RequiredHeadersEntry
	0,  // 9: talon.v1.ReadFileRequest.file:type_name -> talon.v1.FileRef
	27, // 10: talon.v1.ReadFileResponse.file:type_name -> talon.resources.File
	0,  // 11: talon.v1.UpdateFileRequest.file:type_name -> talon.v1.FileRef
	0,  // 12: talon.v1.GetFileMetadataRequest.file:type_name -> talon.v1.FileRef
	24, // 13: talon.v1.ListFilesRequest.purpose:type_name -> talon.resources.FilePurpose
	25, // 14: talon.v1.ListFilesRequest.index_policy:type_name -> talon.resources.FileIndexPolicy
	27, // 15: talon.v1.ListFilesResponse.files:type_name -> talon.resources.File
	0,  // 16: talon.v1.DeleteFileRequest.file:type_name -> talon.v1.FileRef
	24, // 17: talon.v1.PromoteArtifactRequest.purpose:type_name -> talon.resources.FilePurpose
	25, // 18: talon.v1.PromoteArtifactRequest.index_policy:type_name -> talon.resources.FileIndexPolicy
	26, // 19: talon.v1.PromoteArtifactRequest.retention:type_name -> talon.resources.FileRetention
	27, // 20: talon.v1.FileResponse.file:type_name -> talon.resources.File
	28, // 21: talon.v1.ReadArtifactResponse.artifact:type_name -> talon.data.Artifact
	28, // 22: talon.v1.ListArtifactsResponse.artifacts:type_name -> talon.data.Artifact
	28, // 23: talon.v1.ArtifactResponse.artifact:type_name -> talon.data.Artifact
	1,  // 24: talon.v1.FileService.CreateFile:input_type -> talon.v1.CreateFileRequest
	2,  // 25: talon.v1.FileService.PrepareFileUpload:input_type -> talon.v1.PrepareFileUploadRequest
	4,  // 26: talon.v1.FileService.CompleteFileUpload:input_type -> talon.v1.CompleteFileUploadRequest
	5,  // 27: talon.v1.FileService.ReadFile:input_type -> talon.v1.ReadFileRequest
	7,  // 28: talon.v1.FileService.UpdateFile:input_type -> talon.v1.UpdateFileRequest
	8,  // 29: talon.v1.FileService.GetFileMetadata:input_type -> talon.v1.GetFileMetadataRequest
	9,  // 30: talon.v1.FileService.ListFiles:input_type -> talon.v1.ListFilesRequest
	11, // 31: talon.v1.FileService.DeleteFile:input_type -> talon.v1.DeleteFileRequest
	13, // 32: talon.v1.FileService.PromoteArtifact:input_type -> talon.v1.PromoteArtifactRequest
	15, // 33: talon.v1.ArtifactService.ReadArtifact:input_type -> talon.v1.ReadArtifactRequest
	17, // 34: talon.v1.ArtifactService.GetArtifactMetadata:input_type -> talon.v1.GetArtifactMetadataRequest
	18, // 35: talon.v1.ArtifactService.ListArtifacts:input_type -> talon.v1.ListArtifactsRequest
	20, // 36: talon.v1.ArtifactService.GrantArtifact:input_type -> talon.v1.GrantArtifactRequest
	14, // 37: talon.v1.FileService.CreateFile:output_type -> talon.v1.FileResponse
	3,  // 38: talon.v1.FileService.PrepareFileUpload:output_type -> talon.v1.PrepareFileUploadResponse
	14, // 39: talon.v1.FileService.CompleteFileUpload:output_type -> talon.v1.FileResponse
	6,  // 40: talon.v1.FileService.ReadFile:output_type -> talon.v1.ReadFileResponse
	14, // 41: talon.v1.FileService.UpdateFile:output_type -> talon.v1.FileResponse
	14, // 42: talon.v1.FileService.GetFileMetadata:output_type -> talon.v1.FileResponse
	10, // 43: talon.v1.FileService.ListFiles:output_type -> talon.v1.ListFilesResponse
	12, // 44: talon.v1.FileService.DeleteFile:output_type -> talon.v1.DeleteFileResponse
	14, // 45: talon.v1.FileService.PromoteArtifact:output_type -> talon.v1.FileResponse
	16, // 46: talon.v1.ArtifactService.ReadArtifact:output_type -> talon.v1.ReadArtifactResponse
	21, // 47: talon.v1.ArtifactService.GetArtifactMetadata:output_type -> talon.v1.ArtifactResponse
	19, // 48: talon.v1.ArtifactService.ListArtifacts:output_type -> talon.v1.ListArtifactsResponse
	22, // 49: talon.v1.ArtifactService.GrantArtifact:output_type -> talon.v1.ArtifactUriResponse
	37, // [37:50] is the sub-list for method output_type
	24, // [24:37] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_talon_v1_files_proto_init() }
func file_proto_talon_v1_files_proto_init() {
	if File_proto_talon_v1_files_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_talon_v1_files_proto_rawDesc), len(file_proto_talon_v1_files_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_talon_v1_files_proto_goTypes,
		DependencyIndexes: file_proto_talon_v1_files_proto_depIdxs,
		MessageInfos:      file_proto_talon_v1_files_proto_msgTypes,
	}.Build()
	File_proto_talon_v1_files_proto = out.File
	file_proto_talon_v1_files_proto_goTypes = nil
	file_proto_talon_v1_files_proto_depIdxs = nil
}
