// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/resources/deployments.proto (package talon.resources, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { NamespaceSelector, ResourceCondition, ResourceMeta, ResourceRef } from "./common_pb";
import { file_proto_resources_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/resources/deployments.proto.
 */
export const file_proto_resources_deployments: GenFile = /*@__PURE__*/
  fileDesc("CiFwcm90by9yZXNvdXJjZXMvZGVwbG95bWVudHMucHJvdG8SD3RhbG9uLnJlc291cmNlcyJgCgxUZW1wbGF0ZVNwZWMSDAoEa2luZBgBIAEoCRIvCghtZXRhZGF0YRgCIAEoCzIdLnRhbG9uLnJlc291cmNlcy5SZXNvdXJjZU1ldGESEQoJc3BlY19qc29uGAMgASgJIlUKE0RlcGxveW1lbnRQbGFjZW1lbnQSPgoSbmFtZXNwYWNlX3NlbGVjdG9yGAEgASgLMiIudGFsb24ucmVzb3VyY2VzLk5hbWVzcGFjZVNlbGVjdG9yIlwKDkRlcGxveW1lbnRTcGVjEjcKCXBsYWNlbWVudBgBIAEoCzIkLnRhbG9uLnJlc291cmNlcy5EZXBsb3ltZW50UGxhY2VtZW50EhEKCXRlbXBsYXRlcxgCIAMoCSJnChVEZXBsb3ltZW50UmVwbGljYVNwZWMSNAoOZGVwbG95bWVudF9yZWYYASABKAsyHC50YWxvbi5yZXNvdXJjZXMuUmVzb3VyY2VSZWYSGAoQdGFyZ2V0X25hbWVzcGFjZRgCIAEoCSKmAQoQRGVwbG95bWVudFN0YXR1cxIbChNvYnNlcnZlZF9nZW5lcmF0aW9uGAEgASgEEg0KBXBoYXNlGAIgASgJEjYKCmNvbmRpdGlvbnMYAyADKAsyIi50YWxvbi5yZXNvdXJjZXMuUmVzb3VyY2VDb25kaXRpb24SLgoIcmVwbGljYXMYBCADKAsyHC50YWxvbi5yZXNvdXJjZXMuUmVzb3VyY2VSZWYilwMKF0RlcGxveW1lbnRSZXBsaWNhU3RhdHVzEhoKEnJlbmRlcmVkX3Jlc291cmNlcxgBIAMoCRJVCg9yZW5kZXJlZF9oYXNoZXMYAiADKAsyPC50YWxvbi5yZXNvdXJjZXMuRGVwbG95bWVudFJlcGxpY2FTdGF0dXMuUmVuZGVyZWRIYXNoZXNFbnRyeRIRCgljb25mbGljdHMYAyADKAkSWgoSbGFzdF9yZW5kZXJlZF9qc29uGAQgAygLMj4udGFsb24ucmVzb3VyY2VzLkRlcGxveW1lbnRSZXBsaWNhU3RhdHVzLkxhc3RSZW5kZXJlZEpzb25FbnRyeRIbChNvd25lZF9qc29uX3BvaW50ZXJzGAUgAygJEg0KBXBoYXNlGAYgASgJGjUKE1JlbmRlcmVkSGFzaGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARo3ChVMYXN0UmVuZGVyZWRKc29uRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AWIGcHJvdG8z", [file_proto_resources_common]);

/**
 * @generated from message talon.resources.TemplateSpec
 */
export type TemplateSpec = Message<"talon.resources.TemplateSpec"> & {
  /**
   * @generated from field: string kind = 1;
   */
  kind: string;

  /**
   * @generated from field: talon.resources.ResourceMeta metadata = 2;
   */
  metadata?: ResourceMeta;

  /**
   * @generated from field: string spec_json = 3;
   */
  specJson: string;
};

/**
 * Describes the message talon.resources.TemplateSpec.
 * Use `create(TemplateSpecSchema)` to create a new message.
 */
export const TemplateSpecSchema: GenMessage<TemplateSpec> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 0);

/**
 * @generated from message talon.resources.DeploymentPlacement
 */
export type DeploymentPlacement = Message<"talon.resources.DeploymentPlacement"> & {
  /**
   * @generated from field: talon.resources.NamespaceSelector namespace_selector = 1;
   */
  namespaceSelector?: NamespaceSelector;
};

/**
 * Describes the message talon.resources.DeploymentPlacement.
 * Use `create(DeploymentPlacementSchema)` to create a new message.
 */
export const DeploymentPlacementSchema: GenMessage<DeploymentPlacement> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 1);

/**
 * @generated from message talon.resources.DeploymentSpec
 */
export type DeploymentSpec = Message<"talon.resources.DeploymentSpec"> & {
  /**
   * @generated from field: talon.resources.DeploymentPlacement placement = 1;
   */
  placement?: DeploymentPlacement;

  /**
   * @generated from field: repeated string templates = 2;
   */
  templates: string[];
};

/**
 * Describes the message talon.resources.DeploymentSpec.
 * Use `create(DeploymentSpecSchema)` to create a new message.
 */
export const DeploymentSpecSchema: GenMessage<DeploymentSpec> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 2);

/**
 * @generated from message talon.resources.DeploymentReplicaSpec
 */
export type DeploymentReplicaSpec = Message<"talon.resources.DeploymentReplicaSpec"> & {
  /**
   * @generated from field: talon.resources.ResourceRef deployment_ref = 1;
   */
  deploymentRef?: ResourceRef;

  /**
   * @generated from field: string target_namespace = 2;
   */
  targetNamespace: string;
};

/**
 * Describes the message talon.resources.DeploymentReplicaSpec.
 * Use `create(DeploymentReplicaSpecSchema)` to create a new message.
 */
export const DeploymentReplicaSpecSchema: GenMessage<DeploymentReplicaSpec> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 3);

/**
 * @generated from message talon.resources.DeploymentStatus
 */
export type DeploymentStatus = Message<"talon.resources.DeploymentStatus"> & {
  /**
   * @generated from field: uint64 observed_generation = 1;
   */
  observedGeneration: bigint;

  /**
   * @generated from field: string phase = 2;
   */
  phase: string;

  /**
   * @generated from field: repeated talon.resources.ResourceCondition conditions = 3;
   */
  conditions: ResourceCondition[];

  /**
   * @generated from field: repeated talon.resources.ResourceRef replicas = 4;
   */
  replicas: ResourceRef[];
};

/**
 * Describes the message talon.resources.DeploymentStatus.
 * Use `create(DeploymentStatusSchema)` to create a new message.
 */
export const DeploymentStatusSchema: GenMessage<DeploymentStatus> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 4);

/**
 * @generated from message talon.resources.DeploymentReplicaStatus
 */
export type DeploymentReplicaStatus = Message<"talon.resources.DeploymentReplicaStatus"> & {
  /**
   * @generated from field: repeated string rendered_resources = 1;
   */
  renderedResources: string[];

  /**
   * @generated from field: map<string, string> rendered_hashes = 2;
   */
  renderedHashes: { [key: string]: string };

  /**
   * @generated from field: repeated string conflicts = 3;
   */
  conflicts: string[];

  /**
   * @generated from field: map<string, string> last_rendered_json = 4;
   */
  lastRenderedJson: { [key: string]: string };

  /**
   * @generated from field: repeated string owned_json_pointers = 5;
   */
  ownedJsonPointers: string[];

  /**
   * @generated from field: string phase = 6;
   */
  phase: string;
};

/**
 * Describes the message talon.resources.DeploymentReplicaStatus.
 * Use `create(DeploymentReplicaStatusSchema)` to create a new message.
 */
export const DeploymentReplicaStatusSchema: GenMessage<DeploymentReplicaStatus> = /*@__PURE__*/
  messageDesc(file_proto_resources_deployments, 5);

