// Copyright (C) 2026 Impala Systems, Inc.
// SPDX-License-Identifier: AGPL-3.0-only

use anyhow::Result;
use std::fs;

use super::{Cli, RunOutcome};
use crate::cli::sdk_methods_from_dir;

#[derive(clap::Args)]
pub(crate) struct GenCommand {
    #[arg(long, default_value = "conic/manifests")]
    dir: String,
    #[arg(long, default_value = "client.ts")]
    out: String,
}

pub(super) async fn run(_cli: &Cli, command: &GenCommand) -> Result<RunOutcome> {
    println!("Generating Talon Client SDK from: {}", command.dir);
    let class_methods = sdk_methods_from_dir(&command.dir)?;

    let full_file = format!(
        r#"// Auto-generated by talon-cli gen
export class TalonClient {{
  constructor(private endpoint: string) {{}}

{}
}}
"#,
        class_methods.join("\n\n")
    );

    fs::write(&command.out, full_file)?;
    println!("Wrote API client to {}", command.out);
    Ok(RunOutcome { exit_code: None })
}
