// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/events.proto (package talon.events, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/events.proto.
 */
export const file_proto_events: GenFile = /*@__PURE__*/
  fileDesc("ChJwcm90by9ldmVudHMucHJvdG8SDHRhbG9uLmV2ZW50cyKAAQoOTGlmZWN5Y2xlRXZlbnQSFQoNcmVzb3VyY2VfdHlwZRgBIAEoCRIMCgRuYW1lGAIgASgJEgoKAm5zGAMgASgJEioKBmFjdGlvbhgEIAEoDjIaLnRhbG9uLmV2ZW50cy5TeXN0ZW1BY3Rpb24SEQoJdGltZXN0YW1wGAUgASgDIq8BChNTZXNzaW9uTWVzc2FnZUV2ZW50EhIKCnNlc3Npb25faWQYASABKAkSEgoKbWVzc2FnZV9pZBgCIAEoCRIxCglkaXJlY3Rpb24YAyABKA4yHi50YWxvbi5ldmVudHMuTWVzc2FnZURpcmVjdGlvbhIRCgl0aW1lc3RhbXAYBCABKAMSDQoFYWdlbnQYBSABKAkSDwoHbWVzc2FnZRgGIAEoCRIKCgJucxgHIAEoCSLIAQoQU2Vzc2lvblN0ZXBFdmVudBISCgpzZXNzaW9uX2lkGAEgASgJEikKCXN0ZXBfdHlwZRgCIAEoDjIWLnRhbG9uLmV2ZW50cy5TdGVwVHlwZRIPCgdjb250ZW50GAMgASgJEhEKCXRpbWVzdGFtcBgEIAEoAxINCgVhZ2VudBgFIAEoCRIKCgJucxgGIAEoCRISCgptZXNzYWdlX2lkGAcgASgJEgwKBG5hbWUYCCABKAkSFAoMcGF5bG9hZF9qc29uGAkgASgJKrABCgxTeXN0ZW1BY3Rpb24SHQoZU1lTVEVNX0FDVElPTl9VTlNQRUNJRklFRBAAEhgKFFNZU1RFTV9BQ1RJT05fQ1JFQVRFEAESGAoUU1lTVEVNX0FDVElPTl9VUERBVEUQAhIYChRTWVNURU1fQUNUSU9OX0RFTEVURRADEhkKFVNZU1RFTV9BQ1RJT05fU1VTUEVORBAEEhgKFFNZU1RFTV9BQ1RJT05fUkVTVU1FEAUqdAoQTWVzc2FnZURpcmVjdGlvbhIhCh1NRVNTQUdFX0RJUkVDVElPTl9VTlNQRUNJRklFRBAAEh0KGU1FU1NBR0VfRElSRUNUSU9OX0lOQk9VTkQQARIeChpNRVNTQUdFX0RJUkVDVElPTl9PVVRCT1VORBACKpQBCghTdGVwVHlwZRIZChVTVEVQX1RZUEVfVU5TUEVDSUZJRUQQABITCg9TVEVQX1RZUEVfVE9LRU4QARIUChBTVEVQX1RZUEVfQUNUSU9OEAISGQoVU1RFUF9UWVBFX09CU0VSVkFUSU9OEAMSEgoOU1RFUF9UWVBFX0RPTkUQBBITCg9TVEVQX1RZUEVfRVJST1IQBWIGcHJvdG8z");

/**
 * @generated from message talon.events.LifecycleEvent
 */
export type LifecycleEvent = Message<"talon.events.LifecycleEvent"> & {
  /**
   * @generated from field: string resource_type = 1;
   */
  resourceType: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string ns = 3;
   */
  ns: string;

  /**
   * @generated from field: talon.events.SystemAction action = 4;
   */
  action: SystemAction;

  /**
   * @generated from field: int64 timestamp = 5;
   */
  timestamp: bigint;
};

/**
 * Describes the message talon.events.LifecycleEvent.
 * Use `create(LifecycleEventSchema)` to create a new message.
 */
export const LifecycleEventSchema: GenMessage<LifecycleEvent> = /*@__PURE__*/
  messageDesc(file_proto_events, 0);

/**
 * @generated from message talon.events.SessionMessageEvent
 */
export type SessionMessageEvent = Message<"talon.events.SessionMessageEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string message_id = 2;
   */
  messageId: string;

  /**
   * @generated from field: talon.events.MessageDirection direction = 3;
   */
  direction: MessageDirection;

  /**
   * @generated from field: int64 timestamp = 4;
   */
  timestamp: bigint;

  /**
   * @generated from field: string agent = 5;
   */
  agent: string;

  /**
   * @generated from field: string message = 6;
   */
  message: string;

  /**
   * @generated from field: string ns = 7;
   */
  ns: string;
};

/**
 * Describes the message talon.events.SessionMessageEvent.
 * Use `create(SessionMessageEventSchema)` to create a new message.
 */
export const SessionMessageEventSchema: GenMessage<SessionMessageEvent> = /*@__PURE__*/
  messageDesc(file_proto_events, 1);

/**
 * @generated from message talon.events.SessionStepEvent
 */
export type SessionStepEvent = Message<"talon.events.SessionStepEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: talon.events.StepType step_type = 2;
   */
  stepType: StepType;

  /**
   * @generated from field: string content = 3;
   */
  content: string;

  /**
   * @generated from field: int64 timestamp = 4;
   */
  timestamp: bigint;

  /**
   * @generated from field: string agent = 5;
   */
  agent: string;

  /**
   * @generated from field: string ns = 6;
   */
  ns: string;

  /**
   * @generated from field: string message_id = 7;
   */
  messageId: string;

  /**
   * @generated from field: string name = 8;
   */
  name: string;

  /**
   * @generated from field: string payload_json = 9;
   */
  payloadJson: string;
};

/**
 * Describes the message talon.events.SessionStepEvent.
 * Use `create(SessionStepEventSchema)` to create a new message.
 */
export const SessionStepEventSchema: GenMessage<SessionStepEvent> = /*@__PURE__*/
  messageDesc(file_proto_events, 2);

/**
 * @generated from enum talon.events.SystemAction
 */
export enum SystemAction {
  /**
   * @generated from enum value: SYSTEM_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SYSTEM_ACTION_CREATE = 1;
   */
  CREATE = 1,

  /**
   * @generated from enum value: SYSTEM_ACTION_UPDATE = 2;
   */
  UPDATE = 2,

  /**
   * @generated from enum value: SYSTEM_ACTION_DELETE = 3;
   */
  DELETE = 3,

  /**
   * @generated from enum value: SYSTEM_ACTION_SUSPEND = 4;
   */
  SUSPEND = 4,

  /**
   * @generated from enum value: SYSTEM_ACTION_RESUME = 5;
   */
  RESUME = 5,
}

/**
 * Describes the enum talon.events.SystemAction.
 */
export const SystemActionSchema: GenEnum<SystemAction> = /*@__PURE__*/
  enumDesc(file_proto_events, 0);

/**
 * @generated from enum talon.events.MessageDirection
 */
export enum MessageDirection {
  /**
   * @generated from enum value: MESSAGE_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: MESSAGE_DIRECTION_INBOUND = 1;
   */
  INBOUND = 1,

  /**
   * @generated from enum value: MESSAGE_DIRECTION_OUTBOUND = 2;
   */
  OUTBOUND = 2,
}

/**
 * Describes the enum talon.events.MessageDirection.
 */
export const MessageDirectionSchema: GenEnum<MessageDirection> = /*@__PURE__*/
  enumDesc(file_proto_events, 1);

/**
 * @generated from enum talon.events.StepType
 */
export enum StepType {
  /**
   * @generated from enum value: STEP_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STEP_TYPE_TOKEN = 1;
   */
  TOKEN = 1,

  /**
   * @generated from enum value: STEP_TYPE_ACTION = 2;
   */
  ACTION = 2,

  /**
   * @generated from enum value: STEP_TYPE_OBSERVATION = 3;
   */
  OBSERVATION = 3,

  /**
   * @generated from enum value: STEP_TYPE_DONE = 4;
   */
  DONE = 4,

  /**
   * @generated from enum value: STEP_TYPE_ERROR = 5;
   */
  ERROR = 5,
}

/**
 * Describes the enum talon.events.StepType.
 */
export const StepTypeSchema: GenEnum<StepType> = /*@__PURE__*/
  enumDesc(file_proto_events, 2);

