// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: proto/gateway.proto

package gateway

import (
	context "context"
	data "github.com/impalasys/talon/sdk/go/talon-client/talon/data"
	events "github.com/impalasys/talon/sdk/go/talon-client/talon/events"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_GetKnowledge_FullMethodName            = "/talon.gateway.GatewayService/GetKnowledge"
	GatewayService_SearchKnowledge_FullMethodName         = "/talon.gateway.GatewayService/SearchKnowledge"
	GatewayService_CreateSession_FullMethodName           = "/talon.gateway.GatewayService/CreateSession"
	GatewayService_GetSession_FullMethodName              = "/talon.gateway.GatewayService/GetSession"
	GatewayService_ListSessionMessages_FullMethodName     = "/talon.gateway.GatewayService/ListSessionMessages"
	GatewayService_ListSessions_FullMethodName            = "/talon.gateway.GatewayService/ListSessions"
	GatewayService_DeleteSession_FullMethodName           = "/talon.gateway.GatewayService/DeleteSession"
	GatewayService_ClearSession_FullMethodName            = "/talon.gateway.GatewayService/ClearSession"
	GatewayService_SendMessage_FullMethodName             = "/talon.gateway.GatewayService/SendMessage"
	GatewayService_AppendSessionMessage_FullMethodName    = "/talon.gateway.GatewayService/AppendSessionMessage"
	GatewayService_AnswerSessionPermission_FullMethodName = "/talon.gateway.GatewayService/AnswerSessionPermission"
	GatewayService_StopSessionGeneration_FullMethodName   = "/talon.gateway.GatewayService/StopSessionGeneration"
	GatewayService_StreamSessionParts_FullMethodName      = "/talon.gateway.GatewayService/StreamSessionParts"
	GatewayService_StreamSessionPartsBatch_FullMethodName = "/talon.gateway.GatewayService/StreamSessionPartsBatch"
	GatewayService_PostChannelMessage_FullMethodName      = "/talon.gateway.GatewayService/PostChannelMessage"
	GatewayService_GetChannelMessage_FullMethodName       = "/talon.gateway.GatewayService/GetChannelMessage"
	GatewayService_ListChannelMessages_FullMethodName     = "/talon.gateway.GatewayService/ListChannelMessages"
	GatewayService_StreamChannelEvents_FullMethodName     = "/talon.gateway.GatewayService/StreamChannelEvents"
	GatewayService_CreateWorkflowRun_FullMethodName       = "/talon.gateway.GatewayService/CreateWorkflowRun"
	GatewayService_GetWorkflowRun_FullMethodName          = "/talon.gateway.GatewayService/GetWorkflowRun"
	GatewayService_ListWorkflowRuns_FullMethodName        = "/talon.gateway.GatewayService/ListWorkflowRuns"
	GatewayService_ResumeWorkflowRun_FullMethodName       = "/talon.gateway.GatewayService/ResumeWorkflowRun"
	GatewayService_CancelWorkflowRun_FullMethodName       = "/talon.gateway.GatewayService/CancelWorkflowRun"
	GatewayService_StreamWorkflowEvents_FullMethodName    = "/talon.gateway.GatewayService/StreamWorkflowEvents"
	GatewayService_CreateNamespace_FullMethodName         = "/talon.gateway.GatewayService/CreateNamespace"
	GatewayService_GetNamespace_FullMethodName            = "/talon.gateway.GatewayService/GetNamespace"
	GatewayService_DeleteNamespace_FullMethodName         = "/talon.gateway.GatewayService/DeleteNamespace"
	GatewayService_ListNamespaces_FullMethodName          = "/talon.gateway.GatewayService/ListNamespaces"
	GatewayService_CreateResource_FullMethodName          = "/talon.gateway.GatewayService/CreateResource"
	GatewayService_GetResource_FullMethodName             = "/talon.gateway.GatewayService/GetResource"
	GatewayService_ListResources_FullMethodName           = "/talon.gateway.GatewayService/ListResources"
	GatewayService_DeleteResource_FullMethodName          = "/talon.gateway.GatewayService/DeleteResource"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	// Agent knowledge data-plane queries
	GetKnowledge(ctx context.Context, in *GetKnowledgeRequest, opts ...grpc.CallOption) (*KnowledgeResponse, error)
	SearchKnowledge(ctx context.Context, in *SearchKnowledgeRequest, opts ...grpc.CallOption) (*SearchKnowledgeResponse, error)
	// Agent Sessions
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error)
	// Interactive Comm
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
	AppendSessionMessage(ctx context.Context, in *AppendSessionMessageRequest, opts ...grpc.CallOption) (*AppendSessionMessageResponse, error)
	AnswerSessionPermission(ctx context.Context, in *AnswerSessionPermissionRequest, opts ...grpc.CallOption) (*AnswerSessionPermissionResponse, error)
	StopSessionGeneration(ctx context.Context, in *StopSessionGenerationRequest, opts ...grpc.CallOption) (*StopSessionGenerationResponse, error)
	StreamSessionParts(ctx context.Context, in *StreamSessionPartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.SessionMessagePartEvent], error)
	StreamSessionPartsBatch(ctx context.Context, in *StreamSessionPartsBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.SessionMessagePartEvent], error)
	// Channel data-plane actions
	PostChannelMessage(ctx context.Context, in *PostChannelMessageRequest, opts ...grpc.CallOption) (*PostChannelMessageResponse, error)
	GetChannelMessage(ctx context.Context, in *GetChannelMessageRequest, opts ...grpc.CallOption) (*ChannelMessageResponse, error)
	ListChannelMessages(ctx context.Context, in *ListChannelMessagesRequest, opts ...grpc.CallOption) (*ListChannelMessagesResponse, error)
	StreamChannelEvents(ctx context.Context, in *StreamChannelEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.ChannelEvent], error)
	// Workflow data-plane actions
	CreateWorkflowRun(ctx context.Context, in *CreateWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error)
	GetWorkflowRun(ctx context.Context, in *GetWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error)
	ListWorkflowRuns(ctx context.Context, in *ListWorkflowRunsRequest, opts ...grpc.CallOption) (*ListWorkflowRunsResponse, error)
	ResumeWorkflowRun(ctx context.Context, in *ResumeWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error)
	CancelWorkflowRun(ctx context.Context, in *CancelWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error)
	StreamWorkflowEvents(ctx context.Context, in *StreamWorkflowEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[data.WorkflowRunEvent], error)
	// Namespaces
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	// Generic v2 resources
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) GetKnowledge(ctx context.Context, in *GetKnowledgeRequest, opts ...grpc.CallOption) (*KnowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SearchKnowledge(ctx context.Context, in *SearchKnowledgeRequest, opts ...grpc.CallOption) (*SearchKnowledgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeResponse)
	err := c.cc.Invoke(ctx, GatewayService_SearchKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListSessionMessages(ctx context.Context, in *ListSessionMessagesRequest, opts ...grpc.CallOption) (*ListSessionMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionMessagesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListSessionMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ClearSession(ctx context.Context, in *ClearSessionRequest, opts ...grpc.CallOption) (*ClearSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearSessionResponse)
	err := c.cc.Invoke(ctx, GatewayService_ClearSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AppendSessionMessage(ctx context.Context, in *AppendSessionMessageRequest, opts ...grpc.CallOption) (*AppendSessionMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendSessionMessageResponse)
	err := c.cc.Invoke(ctx, GatewayService_AppendSessionMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AnswerSessionPermission(ctx context.Context, in *AnswerSessionPermissionRequest, opts ...grpc.CallOption) (*AnswerSessionPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerSessionPermissionResponse)
	err := c.cc.Invoke(ctx, GatewayService_AnswerSessionPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StopSessionGeneration(ctx context.Context, in *StopSessionGenerationRequest, opts ...grpc.CallOption) (*StopSessionGenerationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSessionGenerationResponse)
	err := c.cc.Invoke(ctx, GatewayService_StopSessionGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StreamSessionParts(ctx context.Context, in *StreamSessionPartsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.SessionMessagePartEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_StreamSessionParts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSessionPartsRequest, events.SessionMessagePartEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamSessionPartsClient = grpc.ServerStreamingClient[events.SessionMessagePartEvent]

func (c *gatewayServiceClient) StreamSessionPartsBatch(ctx context.Context, in *StreamSessionPartsBatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.SessionMessagePartEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[1], GatewayService_StreamSessionPartsBatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamSessionPartsBatchRequest, events.SessionMessagePartEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamSessionPartsBatchClient = grpc.ServerStreamingClient[events.SessionMessagePartEvent]

func (c *gatewayServiceClient) PostChannelMessage(ctx context.Context, in *PostChannelMessageRequest, opts ...grpc.CallOption) (*PostChannelMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostChannelMessageResponse)
	err := c.cc.Invoke(ctx, GatewayService_PostChannelMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetChannelMessage(ctx context.Context, in *GetChannelMessageRequest, opts ...grpc.CallOption) (*ChannelMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChannelMessageResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetChannelMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListChannelMessages(ctx context.Context, in *ListChannelMessagesRequest, opts ...grpc.CallOption) (*ListChannelMessagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListChannelMessagesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListChannelMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StreamChannelEvents(ctx context.Context, in *StreamChannelEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[events.ChannelEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[2], GatewayService_StreamChannelEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamChannelEventsRequest, events.ChannelEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamChannelEventsClient = grpc.ServerStreamingClient[events.ChannelEvent]

func (c *gatewayServiceClient) CreateWorkflowRun(ctx context.Context, in *CreateWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRunResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateWorkflowRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetWorkflowRun(ctx context.Context, in *GetWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRunResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetWorkflowRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListWorkflowRuns(ctx context.Context, in *ListWorkflowRunsRequest, opts ...grpc.CallOption) (*ListWorkflowRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowRunsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListWorkflowRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ResumeWorkflowRun(ctx context.Context, in *ResumeWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRunResponse)
	err := c.cc.Invoke(ctx, GatewayService_ResumeWorkflowRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CancelWorkflowRun(ctx context.Context, in *CancelWorkflowRunRequest, opts ...grpc.CallOption) (*WorkflowRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowRunResponse)
	err := c.cc.Invoke(ctx, GatewayService_CancelWorkflowRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) StreamWorkflowEvents(ctx context.Context, in *StreamWorkflowEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[data.WorkflowRunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[3], GatewayService_StreamWorkflowEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkflowEventsRequest, data.WorkflowRunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamWorkflowEventsClient = grpc.ServerStreamingClient[data.WorkflowRunEvent]

func (c *gatewayServiceClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*NamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NamespaceResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*ResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResourceResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	// Agent knowledge data-plane queries
	GetKnowledge(context.Context, *GetKnowledgeRequest) (*KnowledgeResponse, error)
	SearchKnowledge(context.Context, *SearchKnowledgeRequest) (*SearchKnowledgeResponse, error)
	// Agent Sessions
	CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error)
	ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error)
	// Interactive Comm
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error)
	AppendSessionMessage(context.Context, *AppendSessionMessageRequest) (*AppendSessionMessageResponse, error)
	AnswerSessionPermission(context.Context, *AnswerSessionPermissionRequest) (*AnswerSessionPermissionResponse, error)
	StopSessionGeneration(context.Context, *StopSessionGenerationRequest) (*StopSessionGenerationResponse, error)
	StreamSessionParts(*StreamSessionPartsRequest, grpc.ServerStreamingServer[events.SessionMessagePartEvent]) error
	StreamSessionPartsBatch(*StreamSessionPartsBatchRequest, grpc.ServerStreamingServer[events.SessionMessagePartEvent]) error
	// Channel data-plane actions
	PostChannelMessage(context.Context, *PostChannelMessageRequest) (*PostChannelMessageResponse, error)
	GetChannelMessage(context.Context, *GetChannelMessageRequest) (*ChannelMessageResponse, error)
	ListChannelMessages(context.Context, *ListChannelMessagesRequest) (*ListChannelMessagesResponse, error)
	StreamChannelEvents(*StreamChannelEventsRequest, grpc.ServerStreamingServer[events.ChannelEvent]) error
	// Workflow data-plane actions
	CreateWorkflowRun(context.Context, *CreateWorkflowRunRequest) (*WorkflowRunResponse, error)
	GetWorkflowRun(context.Context, *GetWorkflowRunRequest) (*WorkflowRunResponse, error)
	ListWorkflowRuns(context.Context, *ListWorkflowRunsRequest) (*ListWorkflowRunsResponse, error)
	ResumeWorkflowRun(context.Context, *ResumeWorkflowRunRequest) (*WorkflowRunResponse, error)
	CancelWorkflowRun(context.Context, *CancelWorkflowRunRequest) (*WorkflowRunResponse, error)
	StreamWorkflowEvents(*StreamWorkflowEventsRequest, grpc.ServerStreamingServer[data.WorkflowRunEvent]) error
	// Namespaces
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*NamespaceResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*NamespaceResponse, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*NamespaceResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	// Generic v2 resources
	CreateResource(context.Context, *CreateResourceRequest) (*ResourceResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*ResourceResponse, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) GetKnowledge(context.Context, *GetKnowledgeRequest) (*KnowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKnowledge not implemented")
}
func (UnimplementedGatewayServiceServer) SearchKnowledge(context.Context, *SearchKnowledgeRequest) (*SearchKnowledgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedGatewayServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedGatewayServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedGatewayServiceServer) ListSessionMessages(context.Context, *ListSessionMessagesRequest) (*ListSessionMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessionMessages not implemented")
}
func (UnimplementedGatewayServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedGatewayServiceServer) ClearSession(context.Context, *ClearSessionRequest) (*ClearSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearSession not implemented")
}
func (UnimplementedGatewayServiceServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGatewayServiceServer) AppendSessionMessage(context.Context, *AppendSessionMessageRequest) (*AppendSessionMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendSessionMessage not implemented")
}
func (UnimplementedGatewayServiceServer) AnswerSessionPermission(context.Context, *AnswerSessionPermissionRequest) (*AnswerSessionPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerSessionPermission not implemented")
}
func (UnimplementedGatewayServiceServer) StopSessionGeneration(context.Context, *StopSessionGenerationRequest) (*StopSessionGenerationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSessionGeneration not implemented")
}
func (UnimplementedGatewayServiceServer) StreamSessionParts(*StreamSessionPartsRequest, grpc.ServerStreamingServer[events.SessionMessagePartEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSessionParts not implemented")
}
func (UnimplementedGatewayServiceServer) StreamSessionPartsBatch(*StreamSessionPartsBatchRequest, grpc.ServerStreamingServer[events.SessionMessagePartEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamSessionPartsBatch not implemented")
}
func (UnimplementedGatewayServiceServer) PostChannelMessage(context.Context, *PostChannelMessageRequest) (*PostChannelMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostChannelMessage not implemented")
}
func (UnimplementedGatewayServiceServer) GetChannelMessage(context.Context, *GetChannelMessageRequest) (*ChannelMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChannelMessage not implemented")
}
func (UnimplementedGatewayServiceServer) ListChannelMessages(context.Context, *ListChannelMessagesRequest) (*ListChannelMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChannelMessages not implemented")
}
func (UnimplementedGatewayServiceServer) StreamChannelEvents(*StreamChannelEventsRequest, grpc.ServerStreamingServer[events.ChannelEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamChannelEvents not implemented")
}
func (UnimplementedGatewayServiceServer) CreateWorkflowRun(context.Context, *CreateWorkflowRunRequest) (*WorkflowRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWorkflowRun not implemented")
}
func (UnimplementedGatewayServiceServer) GetWorkflowRun(context.Context, *GetWorkflowRunRequest) (*WorkflowRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowRun not implemented")
}
func (UnimplementedGatewayServiceServer) ListWorkflowRuns(context.Context, *ListWorkflowRunsRequest) (*ListWorkflowRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkflowRuns not implemented")
}
func (UnimplementedGatewayServiceServer) ResumeWorkflowRun(context.Context, *ResumeWorkflowRunRequest) (*WorkflowRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeWorkflowRun not implemented")
}
func (UnimplementedGatewayServiceServer) CancelWorkflowRun(context.Context, *CancelWorkflowRunRequest) (*WorkflowRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelWorkflowRun not implemented")
}
func (UnimplementedGatewayServiceServer) StreamWorkflowEvents(*StreamWorkflowEventsRequest, grpc.ServerStreamingServer[data.WorkflowRunEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWorkflowEvents not implemented")
}
func (UnimplementedGatewayServiceServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*NamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedGatewayServiceServer) GetNamespace(context.Context, *GetNamespaceRequest) (*NamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNamespace not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*NamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedGatewayServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedGatewayServiceServer) CreateResource(context.Context, *CreateResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResource not implemented")
}
func (UnimplementedGatewayServiceServer) GetResource(context.Context, *GetResourceRequest) (*ResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResource not implemented")
}
func (UnimplementedGatewayServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_GetKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetKnowledge(ctx, req.(*GetKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SearchKnowledge(ctx, req.(*SearchKnowledgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListSessionMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListSessionMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListSessionMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListSessionMessages(ctx, req.(*ListSessionMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ClearSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ClearSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ClearSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ClearSession(ctx, req.(*ClearSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AppendSessionMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendSessionMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AppendSessionMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AppendSessionMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AppendSessionMessage(ctx, req.(*AppendSessionMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AnswerSessionPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerSessionPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AnswerSessionPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AnswerSessionPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AnswerSessionPermission(ctx, req.(*AnswerSessionPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StopSessionGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).StopSessionGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_StopSessionGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).StopSessionGeneration(ctx, req.(*StopSessionGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StreamSessionParts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSessionPartsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).StreamSessionParts(m, &grpc.GenericServerStream[StreamSessionPartsRequest, events.SessionMessagePartEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamSessionPartsServer = grpc.ServerStreamingServer[events.SessionMessagePartEvent]

func _GatewayService_StreamSessionPartsBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamSessionPartsBatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).StreamSessionPartsBatch(m, &grpc.GenericServerStream[StreamSessionPartsBatchRequest, events.SessionMessagePartEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamSessionPartsBatchServer = grpc.ServerStreamingServer[events.SessionMessagePartEvent]

func _GatewayService_PostChannelMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostChannelMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PostChannelMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PostChannelMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PostChannelMessage(ctx, req.(*PostChannelMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetChannelMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChannelMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetChannelMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetChannelMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetChannelMessage(ctx, req.(*GetChannelMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListChannelMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChannelMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListChannelMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListChannelMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListChannelMessages(ctx, req.(*ListChannelMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StreamChannelEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamChannelEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).StreamChannelEvents(m, &grpc.GenericServerStream[StreamChannelEventsRequest, events.ChannelEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamChannelEventsServer = grpc.ServerStreamingServer[events.ChannelEvent]

func _GatewayService_CreateWorkflowRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateWorkflowRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateWorkflowRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateWorkflowRun(ctx, req.(*CreateWorkflowRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetWorkflowRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetWorkflowRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetWorkflowRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetWorkflowRun(ctx, req.(*GetWorkflowRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListWorkflowRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListWorkflowRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListWorkflowRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListWorkflowRuns(ctx, req.(*ListWorkflowRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ResumeWorkflowRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeWorkflowRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ResumeWorkflowRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ResumeWorkflowRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ResumeWorkflowRun(ctx, req.(*ResumeWorkflowRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CancelWorkflowRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelWorkflowRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CancelWorkflowRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CancelWorkflowRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CancelWorkflowRun(ctx, req.(*CancelWorkflowRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_StreamWorkflowEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkflowEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).StreamWorkflowEvents(m, &grpc.GenericServerStream[StreamWorkflowEventsRequest, data.WorkflowRunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_StreamWorkflowEventsServer = grpc.ServerStreamingServer[data.WorkflowRunEvent]

func _GatewayService_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetNamespace(ctx, req.(*GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateResource(ctx, req.(*CreateResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetResource(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "talon.gateway.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKnowledge",
			Handler:    _GatewayService_GetKnowledge_Handler,
		},
		{
			MethodName: "SearchKnowledge",
			Handler:    _GatewayService_SearchKnowledge_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _GatewayService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _GatewayService_GetSession_Handler,
		},
		{
			MethodName: "ListSessionMessages",
			Handler:    _GatewayService_ListSessionMessages_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _GatewayService_ListSessions_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _GatewayService_DeleteSession_Handler,
		},
		{
			MethodName: "ClearSession",
			Handler:    _GatewayService_ClearSession_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _GatewayService_SendMessage_Handler,
		},
		{
			MethodName: "AppendSessionMessage",
			Handler:    _GatewayService_AppendSessionMessage_Handler,
		},
		{
			MethodName: "AnswerSessionPermission",
			Handler:    _GatewayService_AnswerSessionPermission_Handler,
		},
		{
			MethodName: "StopSessionGeneration",
			Handler:    _GatewayService_StopSessionGeneration_Handler,
		},
		{
			MethodName: "PostChannelMessage",
			Handler:    _GatewayService_PostChannelMessage_Handler,
		},
		{
			MethodName: "GetChannelMessage",
			Handler:    _GatewayService_GetChannelMessage_Handler,
		},
		{
			MethodName: "ListChannelMessages",
			Handler:    _GatewayService_ListChannelMessages_Handler,
		},
		{
			MethodName: "CreateWorkflowRun",
			Handler:    _GatewayService_CreateWorkflowRun_Handler,
		},
		{
			MethodName: "GetWorkflowRun",
			Handler:    _GatewayService_GetWorkflowRun_Handler,
		},
		{
			MethodName: "ListWorkflowRuns",
			Handler:    _GatewayService_ListWorkflowRuns_Handler,
		},
		{
			MethodName: "ResumeWorkflowRun",
			Handler:    _GatewayService_ResumeWorkflowRun_Handler,
		},
		{
			MethodName: "CancelWorkflowRun",
			Handler:    _GatewayService_CancelWorkflowRun_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _GatewayService_CreateNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _GatewayService_GetNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _GatewayService_DeleteNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _GatewayService_ListNamespaces_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _GatewayService_CreateResource_Handler,
		},
		{
			MethodName: "GetResource",
			Handler:    _GatewayService_GetResource_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _GatewayService_ListResources_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _GatewayService_DeleteResource_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSessionParts",
			Handler:       _GatewayService_StreamSessionParts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamSessionPartsBatch",
			Handler:       _GatewayService_StreamSessionPartsBatch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamChannelEvents",
			Handler:       _GatewayService_StreamChannelEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWorkflowEvents",
			Handler:       _GatewayService_StreamWorkflowEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/gateway.proto",
}
