// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/data/data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRole int32

const (
	MessageRole_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_ROLE_USER        MessageRole = 1
	MessageRole_ROLE_ASSISTANT   MessageRole = 2
	MessageRole_ROLE_SYSTEM      MessageRole = 3
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ASSISTANT",
		3: "ROLE_SYSTEM",
	}
	MessageRole_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ASSISTANT":   2,
		"ROLE_SYSTEM":      3,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_data_proto_enumTypes[0].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_proto_data_data_proto_enumTypes[0]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{0}
}

type SessionMessagePartType int32

const (
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_UNSPECIFIED        SessionMessagePartType = 0
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_TEXT               SessionMessagePartType = 1
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_REASONING          SessionMessagePartType = 2
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_TOOL_CALL          SessionMessagePartType = 3
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_TOOL_RESULT        SessionMessagePartType = 4
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_USAGE              SessionMessagePartType = 5
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_ERROR              SessionMessagePartType = 6
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_IMAGE              SessionMessagePartType = 7
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_AUDIO              SessionMessagePartType = 8
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_VIDEO              SessionMessagePartType = 9
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_FILE               SessionMessagePartType = 10
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_REQUEST_PERMISSION SessionMessagePartType = 11
	SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_PERMISSION_RESULT  SessionMessagePartType = 12
)

// Enum value maps for SessionMessagePartType.
var (
	SessionMessagePartType_name = map[int32]string{
		0:  "SESSION_MESSAGE_PART_TYPE_UNSPECIFIED",
		1:  "SESSION_MESSAGE_PART_TYPE_TEXT",
		2:  "SESSION_MESSAGE_PART_TYPE_REASONING",
		3:  "SESSION_MESSAGE_PART_TYPE_TOOL_CALL",
		4:  "SESSION_MESSAGE_PART_TYPE_TOOL_RESULT",
		5:  "SESSION_MESSAGE_PART_TYPE_USAGE",
		6:  "SESSION_MESSAGE_PART_TYPE_ERROR",
		7:  "SESSION_MESSAGE_PART_TYPE_IMAGE",
		8:  "SESSION_MESSAGE_PART_TYPE_AUDIO",
		9:  "SESSION_MESSAGE_PART_TYPE_VIDEO",
		10: "SESSION_MESSAGE_PART_TYPE_FILE",
		11: "SESSION_MESSAGE_PART_TYPE_REQUEST_PERMISSION",
		12: "SESSION_MESSAGE_PART_TYPE_PERMISSION_RESULT",
	}
	SessionMessagePartType_value = map[string]int32{
		"SESSION_MESSAGE_PART_TYPE_UNSPECIFIED":        0,
		"SESSION_MESSAGE_PART_TYPE_TEXT":               1,
		"SESSION_MESSAGE_PART_TYPE_REASONING":          2,
		"SESSION_MESSAGE_PART_TYPE_TOOL_CALL":          3,
		"SESSION_MESSAGE_PART_TYPE_TOOL_RESULT":        4,
		"SESSION_MESSAGE_PART_TYPE_USAGE":              5,
		"SESSION_MESSAGE_PART_TYPE_ERROR":              6,
		"SESSION_MESSAGE_PART_TYPE_IMAGE":              7,
		"SESSION_MESSAGE_PART_TYPE_AUDIO":              8,
		"SESSION_MESSAGE_PART_TYPE_VIDEO":              9,
		"SESSION_MESSAGE_PART_TYPE_FILE":               10,
		"SESSION_MESSAGE_PART_TYPE_REQUEST_PERMISSION": 11,
		"SESSION_MESSAGE_PART_TYPE_PERMISSION_RESULT":  12,
	}
)

func (x SessionMessagePartType) Enum() *SessionMessagePartType {
	p := new(SessionMessagePartType)
	*p = x
	return p
}

func (x SessionMessagePartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMessagePartType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_data_proto_enumTypes[1].Descriptor()
}

func (SessionMessagePartType) Type() protoreflect.EnumType {
	return &file_proto_data_data_proto_enumTypes[1]
}

func (x SessionMessagePartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMessagePartType.Descriptor instead.
func (SessionMessagePartType) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{1}
}

type ObjectRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MediaType       string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	SizeBytes       uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256          string                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Filename        string                 `protobuf:"bytes,5,opt,name=filename,proto3" json:"filename,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentEncoding string                 `protobuf:"bytes,7,opt,name=content_encoding,json=contentEncoding,proto3" json:"content_encoding,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObjectRef) Reset() {
	*x = ObjectRef{}
	mi := &file_proto_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRef) ProtoMessage() {}

func (x *ObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRef.ProtoReflect.Descriptor instead.
func (*ObjectRef) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ObjectRef) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ObjectRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ObjectRef) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ObjectRef) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ObjectRef) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ObjectRef) GetContentEncoding() string {
	if x != nil {
		return x.ContentEncoding
	}
	return ""
}

type Artifact struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Path           string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	MediaType      string                 `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	ObjectRef      *ObjectRef             `protobuf:"bytes,6,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	CreatedByAgent string                 `protobuf:"bytes,7,opt,name=created_by_agent,json=createdByAgent,proto3" json:"created_by_agent,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_proto_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Artifact) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artifact) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Artifact) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *Artifact) GetObjectRef() *ObjectRef {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

func (x *Artifact) GetCreatedByAgent() string {
	if x != nil {
		return x.CreatedByAgent
	}
	return ""
}

func (x *Artifact) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Artifact) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Artifact) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HandleGrant struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind              string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	TargetId          string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Agent             string                 `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent,omitempty"`
	SessionId         string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Operations        []string               `protobuf:"bytes,7,rep,name=operations,proto3" json:"operations,omitempty"`
	AudienceAgent     string                 `protobuf:"bytes,8,opt,name=audience_agent,json=audienceAgent,proto3" json:"audience_agent,omitempty"`
	AudienceSessionId string                 `protobuf:"bytes,9,opt,name=audience_session_id,json=audienceSessionId,proto3" json:"audience_session_id,omitempty"`
	ExpiresAt         int64                  `protobuf:"varint,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandleGrant) Reset() {
	*x = HandleGrant{}
	mi := &file_proto_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleGrant) ProtoMessage() {}

func (x *HandleGrant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleGrant.ProtoReflect.Descriptor instead.
func (*HandleGrant) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *HandleGrant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HandleGrant) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *HandleGrant) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *HandleGrant) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *HandleGrant) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *HandleGrant) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandleGrant) GetOperations() []string {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *HandleGrant) GetAudienceAgent() string {
	if x != nil {
		return x.AudienceAgent
	}
	return ""
}

func (x *HandleGrant) GetAudienceSessionId() string {
	if x != nil {
		return x.AudienceSessionId
	}
	return ""
}

func (x *HandleGrant) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *HandleGrant) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable provider-native principal identifier when available, such as a
	// Slack user ID or iMessage handle GUID.
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// Human-addressable identity when available, such as email, phone number, or
	// iMessage handle.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Display name captured from the provider at event time.
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Normalized principal kind, such as user, bot, app, or system.
	Kind string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// Provider-specific identity metadata that does not justify a first-class
	// protocol field.
	Metadata      map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_proto_data_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{3}
}

func (x *Principal) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Principal) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Principal) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Principal) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Principal) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SessionMessagePart struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PartType    SessionMessagePartType `protobuf:"varint,2,opt,name=part_type,json=partType,proto3,enum=talon.data.SessionMessagePartType" json:"part_type,omitempty"`
	Content     string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt     int64      `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Object        *ObjectRef `protobuf:"bytes,7,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessagePart) Reset() {
	*x = SessionMessagePart{}
	mi := &file_proto_data_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessagePart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessagePart) ProtoMessage() {}

func (x *SessionMessagePart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessagePart.ProtoReflect.Descriptor instead.
func (*SessionMessagePart) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{4}
}

func (x *SessionMessagePart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionMessagePart) GetPartType() SessionMessagePartType {
	if x != nil {
		return x.PartType
	}
	return SessionMessagePartType_SESSION_MESSAGE_PART_TYPE_UNSPECIFIED
}

func (x *SessionMessagePart) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SessionMessagePart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SessionMessagePart) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *SessionMessagePart) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionMessagePart) GetObject() *ObjectRef {
	if x != nil {
		return x.Object
	}
	return nil
}

type SessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role  MessageRole            `protobuf:"varint,2,opt,name=role,proto3,enum=talon.data.MessageRole" json:"role,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt     int64                 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Labels        map[string]string     `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Parts         []*SessionMessagePart `protobuf:"bytes,6,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_proto_data_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{5}
}

func (x *SessionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionMessage) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_ROLE_UNSPECIFIED
}

func (x *SessionMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionMessage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SessionMessage) GetParts() []*SessionMessagePart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type Session struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Agent  string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Ns     string                 `protobuf:"bytes,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Status string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt int64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp in microseconds.
	LastActive    int64             `protobuf:"varint,6,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_data_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{6}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *Session) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *Session) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *Session) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Session) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ChannelMessage struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ns         string                 `protobuf:"bytes,2,opt,name=ns,proto3" json:"ns,omitempty"`
	Channel    string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	AuthorKind string                 `protobuf:"bytes,4,opt,name=author_kind,json=authorKind,proto3" json:"author_kind,omitempty"`
	Author     string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Content    string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt       int64             `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SourceAgent     string            `protobuf:"bytes,8,opt,name=source_agent,json=sourceAgent,proto3" json:"source_agent,omitempty"`
	SourceSessionId string            `protobuf:"bytes,9,opt,name=source_session_id,json=sourceSessionId,proto3" json:"source_session_id,omitempty"`
	Labels          map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_proto_data_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{7}
}

func (x *ChannelMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChannelMessage) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *ChannelMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelMessage) GetAuthorKind() string {
	if x != nil {
		return x.AuthorKind
	}
	return ""
}

func (x *ChannelMessage) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChannelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChannelMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ChannelMessage) GetSourceAgent() string {
	if x != nil {
		return x.SourceAgent
	}
	return ""
}

func (x *ChannelMessage) GetSourceSessionId() string {
	if x != nil {
		return x.SourceSessionId
	}
	return ""
}

func (x *ChannelMessage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Knowledge struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Unix timestamp in microseconds.
	UpdatedAt     int64  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Knowledge) Reset() {
	*x = Knowledge{}
	mi := &file_proto_data_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Knowledge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Knowledge) ProtoMessage() {}

func (x *Knowledge) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Knowledge.ProtoReflect.Descriptor instead.
func (*Knowledge) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{8}
}

func (x *Knowledge) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Knowledge) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Knowledge) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Knowledge) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Knowledge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KnowledgeSearchResult struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Snippet string                 `protobuf:"bytes,2,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score   float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	// Unix timestamp in microseconds.
	Timestamp     int64  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Namespace     string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSearchResult) Reset() {
	*x = KnowledgeSearchResult{}
	mi := &file_proto_data_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSearchResult) ProtoMessage() {}

func (x *KnowledgeSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSearchResult.ProtoReflect.Descriptor instead.
func (*KnowledgeSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{9}
}

func (x *KnowledgeSearchResult) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *KnowledgeSearchResult) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *KnowledgeSearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *KnowledgeSearchResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KnowledgeSearchResult) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type WorkflowRun struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Workflow   string                 `protobuf:"bytes,2,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Ns         string                 `protobuf:"bytes,3,opt,name=ns,proto3" json:"ns,omitempty"`
	Status     string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InputJson  string                 `protobuf:"bytes,5,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	StateJson  string                 `protobuf:"bytes,6,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	OutputJson string                 `protobuf:"bytes,7,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp in microseconds.
	UpdatedAt int64             `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Labels    map[string]string `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Unix timestamp in microseconds.
	ClaimExpiresAt     *int64 `protobuf:"varint,11,opt,name=claim_expires_at,json=claimExpiresAt,proto3,oneof" json:"claim_expires_at,omitempty"`
	Error              string `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	SpecJson           string `protobuf:"bytes,13,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	WorkflowRevision   uint64 `protobuf:"varint,14,opt,name=workflow_revision,json=workflowRevision,proto3" json:"workflow_revision,omitempty"`
	ClaimOwner         string `protobuf:"bytes,15,opt,name=claim_owner,json=claimOwner,proto3" json:"claim_owner,omitempty"`
	ClaimAttempt       uint32 `protobuf:"varint,16,opt,name=claim_attempt,json=claimAttempt,proto3" json:"claim_attempt,omitempty"`
	LastDispatchReason string `protobuf:"bytes,17,opt,name=last_dispatch_reason,json=lastDispatchReason,proto3" json:"last_dispatch_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowRun) Reset() {
	*x = WorkflowRun{}
	mi := &file_proto_data_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRun) ProtoMessage() {}

func (x *WorkflowRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRun.ProtoReflect.Descriptor instead.
func (*WorkflowRun) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowRun) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *WorkflowRun) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *WorkflowRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowRun) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *WorkflowRun) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

func (x *WorkflowRun) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *WorkflowRun) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WorkflowRun) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WorkflowRun) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *WorkflowRun) GetClaimExpiresAt() int64 {
	if x != nil && x.ClaimExpiresAt != nil {
		return *x.ClaimExpiresAt
	}
	return 0
}

func (x *WorkflowRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowRun) GetSpecJson() string {
	if x != nil {
		return x.SpecJson
	}
	return ""
}

func (x *WorkflowRun) GetWorkflowRevision() uint64 {
	if x != nil {
		return x.WorkflowRevision
	}
	return 0
}

func (x *WorkflowRun) GetClaimOwner() string {
	if x != nil {
		return x.ClaimOwner
	}
	return ""
}

func (x *WorkflowRun) GetClaimAttempt() uint32 {
	if x != nil {
		return x.ClaimAttempt
	}
	return 0
}

func (x *WorkflowRun) GetLastDispatchReason() string {
	if x != nil {
		return x.LastDispatchReason
	}
	return ""
}

type WorkflowStepRun struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StepId             string                 `protobuf:"bytes,2,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Attempt            uint32                 `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	InputJson          string                 `protobuf:"bytes,5,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	OutputJson         string                 `protobuf:"bytes,6,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Error              string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ChildSessionId     string                 `protobuf:"bytes,8,opt,name=child_session_id,json=childSessionId,proto3" json:"child_session_id,omitempty"`
	ChildWorkflowRunId string                 `protobuf:"bytes,9,opt,name=child_workflow_run_id,json=childWorkflowRunId,proto3" json:"child_workflow_run_id,omitempty"`
	ResumeJson         string                 `protobuf:"bytes,10,opt,name=resume_json,json=resumeJson,proto3" json:"resume_json,omitempty"`
	SuspendJson        string                 `protobuf:"bytes,11,opt,name=suspend_json,json=suspendJson,proto3" json:"suspend_json,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt int64 `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp in microseconds.
	UpdatedAt int64 `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Unix timestamp in microseconds.
	NextRetryAt *int64 `protobuf:"varint,14,opt,name=next_retry_at,json=nextRetryAt,proto3,oneof" json:"next_retry_at,omitempty"`
	// Unix timestamp in microseconds.
	TimeoutAt        *int64 `protobuf:"varint,15,opt,name=timeout_at,json=timeoutAt,proto3,oneof" json:"timeout_at,omitempty"`
	WaitWakeupHandle string `protobuf:"bytes,16,opt,name=wait_wakeup_handle,json=waitWakeupHandle,proto3" json:"wait_wakeup_handle,omitempty"`
	// Unix timestamp in microseconds.
	WaitUntilAt   *int64 `protobuf:"varint,17,opt,name=wait_until_at,json=waitUntilAt,proto3,oneof" json:"wait_until_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStepRun) Reset() {
	*x = WorkflowStepRun{}
	mi := &file_proto_data_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStepRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStepRun) ProtoMessage() {}

func (x *WorkflowStepRun) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStepRun.ProtoReflect.Descriptor instead.
func (*WorkflowStepRun) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{11}
}

func (x *WorkflowStepRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowStepRun) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *WorkflowStepRun) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *WorkflowStepRun) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStepRun) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *WorkflowStepRun) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *WorkflowStepRun) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowStepRun) GetChildSessionId() string {
	if x != nil {
		return x.ChildSessionId
	}
	return ""
}

func (x *WorkflowStepRun) GetChildWorkflowRunId() string {
	if x != nil {
		return x.ChildWorkflowRunId
	}
	return ""
}

func (x *WorkflowStepRun) GetResumeJson() string {
	if x != nil {
		return x.ResumeJson
	}
	return ""
}

func (x *WorkflowStepRun) GetSuspendJson() string {
	if x != nil {
		return x.SuspendJson
	}
	return ""
}

func (x *WorkflowStepRun) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WorkflowStepRun) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WorkflowStepRun) GetNextRetryAt() int64 {
	if x != nil && x.NextRetryAt != nil {
		return *x.NextRetryAt
	}
	return 0
}

func (x *WorkflowStepRun) GetTimeoutAt() int64 {
	if x != nil && x.TimeoutAt != nil {
		return *x.TimeoutAt
	}
	return 0
}

func (x *WorkflowStepRun) GetWaitWakeupHandle() string {
	if x != nil {
		return x.WaitWakeupHandle
	}
	return ""
}

func (x *WorkflowStepRun) GetWaitUntilAt() int64 {
	if x != nil && x.WaitUntilAt != nil {
		return *x.WaitUntilAt
	}
	return 0
}

type WorkflowRunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ns            string                 `protobuf:"bytes,2,opt,name=ns,proto3" json:"ns,omitempty"`
	Workflow      string                 `protobuf:"bytes,3,opt,name=workflow,proto3" json:"workflow,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	StepId        string                 `protobuf:"bytes,6,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,8,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowRunEvent) Reset() {
	*x = WorkflowRunEvent{}
	mi := &file_proto_data_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRunEvent) ProtoMessage() {}

func (x *WorkflowRunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRunEvent.ProtoReflect.Descriptor instead.
func (*WorkflowRunEvent) Descriptor() ([]byte, []int) {
	return file_proto_data_data_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowRunEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowRunEvent) GetNs() string {
	if x != nil {
		return x.Ns
	}
	return ""
}

func (x *WorkflowRunEvent) GetWorkflow() string {
	if x != nil {
		return x.Workflow
	}
	return ""
}

func (x *WorkflowRunEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowRunEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkflowRunEvent) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *WorkflowRunEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowRunEvent) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *WorkflowRunEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_data_data_proto protoreflect.FileDescriptor

const file_proto_data_data_proto_rawDesc = "" +
	"\n" +
	"\x15proto/data/data.proto\x12\n" +
	"talon.data\"\xb8\x02\n" +
	"\tObjectRef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x1a\n" +
	"\bfilename\x18\x05 \x01(\tR\bfilename\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.talon.data.ObjectRef.MetadataEntryR\bmetadata\x12)\n" +
	"\x10content_encoding\x18\a \x01(\tR\x0fcontentEncoding\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf3\x03\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"media_type\x18\x05 \x01(\tR\tmediaType\x124\n" +
	"\n" +
	"object_ref\x18\x06 \x01(\v2\x15.talon.data.ObjectRefR\tobjectRef\x12(\n" +
	"\x10created_by_agent\x18\a \x01(\tR\x0ecreatedByAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x128\n" +
	"\x06labels\x18\t \x03(\v2 .talon.data.Artifact.LabelsEntryR\x06labels\x12>\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\".talon.data.Artifact.MetadataEntryR\bmetadata\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x02\n" +
	"\vHandleGrant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x14\n" +
	"\x05agent\x18\x05 \x01(\tR\x05agent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"operations\x18\a \x03(\tR\n" +
	"operations\x12%\n" +
	"\x0eaudience_agent\x18\b \x01(\tR\raudienceAgent\x12.\n" +
	"\x13audience_session_id\x18\t \x01(\tR\x11audienceSessionId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\"\xfb\x01\n" +
	"\tPrincipal\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12?\n" +
	"\bmetadata\x18\x05 \x03(\v2#.talon.data.Principal.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x12SessionMessagePart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12?\n" +
	"\tpart_type\x18\x02 \x01(\x0e2\".talon.data.SessionMessagePartTypeR\bpartType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12-\n" +
	"\x06object\x18\a \x01(\v2\x15.talon.data.ObjectRefR\x06object\"\xa3\x02\n" +
	"\x0eSessionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04role\x18\x02 \x01(\x0e2\x17.talon.data.MessageRoleR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.talon.data.SessionMessage.LabelsEntryR\x06labels\x124\n" +
	"\x05parts\x18\x06 \x03(\v2\x1e.talon.data.SessionMessagePartR\x05parts\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x03\x10\x04\"\x87\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\tR\x02ns\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vlast_active\x18\x06 \x01(\x03R\n" +
	"lastActive\x12=\n" +
	"\bmetadata\x18\a \x03(\v2!.talon.data.Session.MetadataEntryR\bmetadata\x127\n" +
	"\x06labels\x18\b \x03(\v2\x1f.talon.data.Session.LabelsEntryR\x06labels\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x03\n" +
	"\x0eChannelMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ns\x18\x02 \x01(\tR\x02ns\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1f\n" +
	"\vauthor_kind\x18\x04 \x01(\tR\n" +
	"authorKind\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12!\n" +
	"\fsource_agent\x18\b \x01(\tR\vsourceAgent\x12*\n" +
	"\x11source_session_id\x18\t \x01(\tR\x0fsourceSessionId\x12>\n" +
	"\x06labels\x18\n" +
	" \x03(\v2&.talon.data.ChannelMessage.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\tKnowledge\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"\x97\x01\n" +
	"\x15KnowledgeSearchResult\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\asnippet\x18\x02 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\"\x92\x05\n" +
	"\vWorkflowRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bworkflow\x18\x02 \x01(\tR\bworkflow\x12\x0e\n" +
	"\x02ns\x18\x03 \x01(\tR\x02ns\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"input_json\x18\x05 \x01(\tR\tinputJson\x12\x1d\n" +
	"\n" +
	"state_json\x18\x06 \x01(\tR\tstateJson\x12\x1f\n" +
	"\voutput_json\x18\a \x01(\tR\n" +
	"outputJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12;\n" +
	"\x06labels\x18\n" +
	" \x03(\v2#.talon.data.WorkflowRun.LabelsEntryR\x06labels\x12-\n" +
	"\x10claim_expires_at\x18\v \x01(\x03H\x00R\x0eclaimExpiresAt\x88\x01\x01\x12\x14\n" +
	"\x05error\x18\f \x01(\tR\x05error\x12\x1b\n" +
	"\tspec_json\x18\r \x01(\tR\bspecJson\x12+\n" +
	"\x11workflow_revision\x18\x0e \x01(\x04R\x10workflowRevision\x12\x1f\n" +
	"\vclaim_owner\x18\x0f \x01(\tR\n" +
	"claimOwner\x12#\n" +
	"\rclaim_attempt\x18\x10 \x01(\rR\fclaimAttempt\x120\n" +
	"\x14last_dispatch_reason\x18\x11 \x01(\tR\x12lastDispatchReason\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x13\n" +
	"\x11_claim_expires_at\"\xf8\x04\n" +
	"\x0fWorkflowStepRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\astep_id\x18\x02 \x01(\tR\x06stepId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\rR\aattempt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"input_json\x18\x05 \x01(\tR\tinputJson\x12\x1f\n" +
	"\voutput_json\x18\x06 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12(\n" +
	"\x10child_session_id\x18\b \x01(\tR\x0echildSessionId\x121\n" +
	"\x15child_workflow_run_id\x18\t \x01(\tR\x12childWorkflowRunId\x12\x1f\n" +
	"\vresume_json\x18\n" +
	" \x01(\tR\n" +
	"resumeJson\x12!\n" +
	"\fsuspend_json\x18\v \x01(\tR\vsuspendJson\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\x12'\n" +
	"\rnext_retry_at\x18\x0e \x01(\x03H\x00R\vnextRetryAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"timeout_at\x18\x0f \x01(\x03H\x01R\ttimeoutAt\x88\x01\x01\x12,\n" +
	"\x12wait_wakeup_handle\x18\x10 \x01(\tR\x10waitWakeupHandle\x12'\n" +
	"\rwait_until_at\x18\x11 \x01(\x03H\x02R\vwaitUntilAt\x88\x01\x01B\x10\n" +
	"\x0e_next_retry_atB\r\n" +
	"\v_timeout_atB\x10\n" +
	"\x0e_wait_until_at\"\xed\x01\n" +
	"\x10WorkflowRunEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ns\x18\x02 \x01(\tR\x02ns\x12\x1a\n" +
	"\bworkflow\x18\x03 \x01(\tR\bworkflow\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x17\n" +
	"\astep_id\x18\x06 \x01(\tR\x06stepId\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x12!\n" +
	"\fpayload_json\x18\b \x01(\tR\vpayloadJson\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp*W\n" +
	"\vMessageRole\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x02\x12\x0f\n" +
	"\vROLE_SYSTEM\x10\x03*\xa4\x04\n" +
	"\x16SessionMessagePartType\x12)\n" +
	"%SESSION_MESSAGE_PART_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSESSION_MESSAGE_PART_TYPE_TEXT\x10\x01\x12'\n" +
	"#SESSION_MESSAGE_PART_TYPE_REASONING\x10\x02\x12'\n" +
	"#SESSION_MESSAGE_PART_TYPE_TOOL_CALL\x10\x03\x12)\n" +
	"%SESSION_MESSAGE_PART_TYPE_TOOL_RESULT\x10\x04\x12#\n" +
	"\x1fSESSION_MESSAGE_PART_TYPE_USAGE\x10\x05\x12#\n" +
	"\x1fSESSION_MESSAGE_PART_TYPE_ERROR\x10\x06\x12#\n" +
	"\x1fSESSION_MESSAGE_PART_TYPE_IMAGE\x10\a\x12#\n" +
	"\x1fSESSION_MESSAGE_PART_TYPE_AUDIO\x10\b\x12#\n" +
	"\x1fSESSION_MESSAGE_PART_TYPE_VIDEO\x10\t\x12\"\n" +
	"\x1eSESSION_MESSAGE_PART_TYPE_FILE\x10\n" +
	"\x120\n" +
	",SESSION_MESSAGE_PART_TYPE_REQUEST_PERMISSION\x10\v\x12/\n" +
	"+SESSION_MESSAGE_PART_TYPE_PERMISSION_RESULT\x10\fb\x06proto3"

var (
	file_proto_data_data_proto_rawDescOnce sync.Once
	file_proto_data_data_proto_rawDescData []byte
)

func file_proto_data_data_proto_rawDescGZIP() []byte {
	file_proto_data_data_proto_rawDescOnce.Do(func() {
		file_proto_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_data_proto_rawDesc), len(file_proto_data_data_proto_rawDesc)))
	})
	return file_proto_data_data_proto_rawDescData
}

var file_proto_data_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_data_data_proto_goTypes = []any{
	(MessageRole)(0),              // 0: talon.data.MessageRole
	(SessionMessagePartType)(0),   // 1: talon.data.SessionMessagePartType
	(*ObjectRef)(nil),             // 2: talon.data.ObjectRef
	(*Artifact)(nil),              // 3: talon.data.Artifact
	(*HandleGrant)(nil),           // 4: talon.data.HandleGrant
	(*Principal)(nil),             // 5: talon.data.Principal
	(*SessionMessagePart)(nil),    // 6: talon.data.SessionMessagePart
	(*SessionMessage)(nil),        // 7: talon.data.SessionMessage
	(*Session)(nil),               // 8: talon.data.Session
	(*ChannelMessage)(nil),        // 9: talon.data.ChannelMessage
	(*Knowledge)(nil),             // 10: talon.data.Knowledge
	(*KnowledgeSearchResult)(nil), // 11: talon.data.KnowledgeSearchResult
	(*WorkflowRun)(nil),           // 12: talon.data.WorkflowRun
	(*WorkflowStepRun)(nil),       // 13: talon.data.WorkflowStepRun
	(*WorkflowRunEvent)(nil),      // 14: talon.data.WorkflowRunEvent
	nil,                           // 15: talon.data.ObjectRef.MetadataEntry
	nil,                           // 16: talon.data.Artifact.LabelsEntry
	nil,                           // 17: talon.data.Artifact.MetadataEntry
	nil,                           // 18: talon.data.Principal.MetadataEntry
	nil,                           // 19: talon.data.SessionMessage.LabelsEntry
	nil,                           // 20: talon.data.Session.MetadataEntry
	nil,                           // 21: talon.data.Session.LabelsEntry
	nil,                           // 22: talon.data.ChannelMessage.LabelsEntry
	nil,                           // 23: talon.data.WorkflowRun.LabelsEntry
}
var file_proto_data_data_proto_depIdxs = []int32{
	15, // 0: talon.data.ObjectRef.metadata:type_name -> talon.data.ObjectRef.MetadataEntry
	2,  // 1: talon.data.Artifact.object_ref:type_name -> talon.data.ObjectRef
	16, // 2: talon.data.Artifact.labels:type_name -> talon.data.Artifact.LabelsEntry
	17, // 3: talon.data.Artifact.metadata:type_name -> talon.data.Artifact.MetadataEntry
	18, // 4: talon.data.Principal.metadata:type_name -> talon.data.Principal.MetadataEntry
	1,  // 5: talon.data.SessionMessagePart.part_type:type_name -> talon.data.SessionMessagePartType
	2,  // 6: talon.data.SessionMessagePart.object:type_name -> talon.data.ObjectRef
	0,  // 7: talon.data.SessionMessage.role:type_name -> talon.data.MessageRole
	19, // 8: talon.data.SessionMessage.labels:type_name -> talon.data.SessionMessage.LabelsEntry
	6,  // 9: talon.data.SessionMessage.parts:type_name -> talon.data.SessionMessagePart
	20, // 10: talon.data.Session.metadata:type_name -> talon.data.Session.MetadataEntry
	21, // 11: talon.data.Session.labels:type_name -> talon.data.Session.LabelsEntry
	22, // 12: talon.data.ChannelMessage.labels:type_name -> talon.data.ChannelMessage.LabelsEntry
	23, // 13: talon.data.WorkflowRun.labels:type_name -> talon.data.WorkflowRun.LabelsEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_data_data_proto_init() }
func file_proto_data_data_proto_init() {
	if File_proto_data_data_proto != nil {
		return
	}
	file_proto_data_data_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_data_data_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_data_proto_rawDesc), len(file_proto_data_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_data_proto_goTypes,
		DependencyIndexes: file_proto_data_data_proto_depIdxs,
		EnumInfos:         file_proto_data_data_proto_enumTypes,
		MessageInfos:      file_proto_data_data_proto_msgTypes,
	}.Build()
	File_proto_data_data_proto = out.File
	file_proto_data_data_proto_goTypes = nil
	file_proto_data_data_proto_depIdxs = nil
}
