// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: proto/data/session_submission.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionSubmissionStatus int32

const (
	// Default value; should not be written for an accepted submission.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_UNSPECIFIED SessionSubmissionStatus = 0
	// The user submission was accepted and durably recorded, but no worker has
	// claimed it yet.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_PENDING SessionSubmissionStatus = 1
	// A worker owns the submission lease and may append journal entries while the
	// lease remains current.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_CLAIMED SessionSubmissionStatus = 2
	// The submission reached a canonical commit boundary and wrote its final
	// assistant SessionMessage. Duplicate deliveries should no-op.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_COMMITTED SessionSubmissionStatus = 3
	// The submission ended with a durable error message or terminal failure.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_FAILED SessionSubmissionStatus = 4
	// The submission was stopped before a normal commit boundary. Recovery policy
	// may inspect the journal to decide whether a later retry is possible.
	SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_INTERRUPTED SessionSubmissionStatus = 5
)

// Enum value maps for SessionSubmissionStatus.
var (
	SessionSubmissionStatus_name = map[int32]string{
		0: "SESSION_SUBMISSION_STATUS_UNSPECIFIED",
		1: "SESSION_SUBMISSION_STATUS_PENDING",
		2: "SESSION_SUBMISSION_STATUS_CLAIMED",
		3: "SESSION_SUBMISSION_STATUS_COMMITTED",
		4: "SESSION_SUBMISSION_STATUS_FAILED",
		5: "SESSION_SUBMISSION_STATUS_INTERRUPTED",
	}
	SessionSubmissionStatus_value = map[string]int32{
		"SESSION_SUBMISSION_STATUS_UNSPECIFIED": 0,
		"SESSION_SUBMISSION_STATUS_PENDING":     1,
		"SESSION_SUBMISSION_STATUS_CLAIMED":     2,
		"SESSION_SUBMISSION_STATUS_COMMITTED":   3,
		"SESSION_SUBMISSION_STATUS_FAILED":      4,
		"SESSION_SUBMISSION_STATUS_INTERRUPTED": 5,
	}
)

func (x SessionSubmissionStatus) Enum() *SessionSubmissionStatus {
	p := new(SessionSubmissionStatus)
	*p = x
	return p
}

func (x SessionSubmissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionSubmissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_session_submission_proto_enumTypes[0].Descriptor()
}

func (SessionSubmissionStatus) Type() protoreflect.EnumType {
	return &file_proto_data_session_submission_proto_enumTypes[0]
}

func (x SessionSubmissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionSubmissionStatus.Descriptor instead.
func (SessionSubmissionStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_session_submission_proto_rawDescGZIP(), []int{0}
}

type SessionSubmission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable idempotency key for one accepted user submission.
	SubmissionId string `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	SessionId    string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Canonical user SessionMessage that caused this submission.
	UserMessageId string `protobuf:"bytes,3,opt,name=user_message_id,json=userMessageId,proto3" json:"user_message_id,omitempty"`
	// Lease/idempotency status for the submission as a whole.
	Status SessionSubmissionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=talon.data.SessionSubmissionStatus" json:"status,omitempty"`
	// Current lease owner. Journal appends are fenced by this value so stale
	// workers cannot move the submission pointer backward.
	AttemptId string `protobuf:"bytes,5,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	// Worker that owns the current claim. Gateways use this to connect to the
	// exact worker process that can stream in-process session parts for the
	// attempt.
	ClaimWorkerId string `protobuf:"bytes,14,opt,name=claim_worker_id,json=claimWorkerId,proto3" json:"claim_worker_id,omitempty"`
	// Number of successful claims/reclaims for this submission.
	AttemptCount uint32 `protobuf:"varint,6,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	// Lease expiration for the current claim. Cleared when the submission becomes
	// terminal.
	// Unix timestamp in microseconds.
	ClaimExpiresAt *int64 `protobuf:"varint,7,opt,name=claim_expires_at,json=claimExpiresAt,proto3,oneof" json:"claim_expires_at,omitempty"`
	// Unix timestamp in microseconds.
	CreatedAt int64 `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Unix timestamp in microseconds.
	UpdatedAt int64 `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Set when the submission reaches a terminal status.
	// Unix timestamp in microseconds.
	CompletedAt *int64 `protobuf:"varint,10,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	// Canonical assistant SessionMessage produced by this submission, when one
	// was committed.
	CommittedMessageId *string `protobuf:"bytes,11,opt,name=committed_message_id,json=committedMessageId,proto3,oneof" json:"committed_message_id,omitempty"`
	// Fast pointer to the latest known execution phase. The append-only
	// SessionJournalEntry list remains authoritative for recovery.
	CurrentPhase SessionExecutionPhase `protobuf:"varint,12,opt,name=current_phase,json=currentPhase,proto3,enum=talon.data.SessionExecutionPhase" json:"current_phase,omitempty"`
	// Fast pointer to the journal entry that supplied current_phase. Recovery may
	// repair this from the latest journal entry if a crash happens between entry
	// append and pointer update.
	CurrentJournalEntryId *string `protobuf:"bytes,13,opt,name=current_journal_entry_id,json=currentJournalEntryId,proto3,oneof" json:"current_journal_entry_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionSubmission) Reset() {
	*x = SessionSubmission{}
	mi := &file_proto_data_session_submission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSubmission) ProtoMessage() {}

func (x *SessionSubmission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_session_submission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSubmission.ProtoReflect.Descriptor instead.
func (*SessionSubmission) Descriptor() ([]byte, []int) {
	return file_proto_data_session_submission_proto_rawDescGZIP(), []int{0}
}

func (x *SessionSubmission) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *SessionSubmission) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSubmission) GetUserMessageId() string {
	if x != nil {
		return x.UserMessageId
	}
	return ""
}

func (x *SessionSubmission) GetStatus() SessionSubmissionStatus {
	if x != nil {
		return x.Status
	}
	return SessionSubmissionStatus_SESSION_SUBMISSION_STATUS_UNSPECIFIED
}

func (x *SessionSubmission) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *SessionSubmission) GetClaimWorkerId() string {
	if x != nil {
		return x.ClaimWorkerId
	}
	return ""
}

func (x *SessionSubmission) GetAttemptCount() uint32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *SessionSubmission) GetClaimExpiresAt() int64 {
	if x != nil && x.ClaimExpiresAt != nil {
		return *x.ClaimExpiresAt
	}
	return 0
}

func (x *SessionSubmission) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionSubmission) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *SessionSubmission) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

func (x *SessionSubmission) GetCommittedMessageId() string {
	if x != nil && x.CommittedMessageId != nil {
		return *x.CommittedMessageId
	}
	return ""
}

func (x *SessionSubmission) GetCurrentPhase() SessionExecutionPhase {
	if x != nil {
		return x.CurrentPhase
	}
	return SessionExecutionPhase_SESSION_EXECUTION_PHASE_UNSPECIFIED
}

func (x *SessionSubmission) GetCurrentJournalEntryId() string {
	if x != nil && x.CurrentJournalEntryId != nil {
		return *x.CurrentJournalEntryId
	}
	return ""
}

var File_proto_data_session_submission_proto protoreflect.FileDescriptor

const file_proto_data_session_submission_proto_rawDesc = "" +
	"\n" +
	"#proto/data/session_submission.proto\x12\n" +
	"talon.data\x1a&proto/data/session_journal_entry.proto\"\xd6\x05\n" +
	"\x11SessionSubmission\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12&\n" +
	"\x0fuser_message_id\x18\x03 \x01(\tR\ruserMessageId\x12;\n" +
	"\x06status\x18\x04 \x01(\x0e2#.talon.data.SessionSubmissionStatusR\x06status\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x05 \x01(\tR\tattemptId\x12&\n" +
	"\x0fclaim_worker_id\x18\x0e \x01(\tR\rclaimWorkerId\x12#\n" +
	"\rattempt_count\x18\x06 \x01(\rR\fattemptCount\x12-\n" +
	"\x10claim_expires_at\x18\a \x01(\x03H\x00R\x0eclaimExpiresAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12&\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\x03H\x01R\vcompletedAt\x88\x01\x01\x125\n" +
	"\x14committed_message_id\x18\v \x01(\tH\x02R\x12committedMessageId\x88\x01\x01\x12F\n" +
	"\rcurrent_phase\x18\f \x01(\x0e2!.talon.data.SessionExecutionPhaseR\fcurrentPhase\x12<\n" +
	"\x18current_journal_entry_id\x18\r \x01(\tH\x03R\x15currentJournalEntryId\x88\x01\x01B\x13\n" +
	"\x11_claim_expires_atB\x0f\n" +
	"\r_completed_atB\x17\n" +
	"\x15_committed_message_idB\x1b\n" +
	"\x19_current_journal_entry_id*\x8c\x02\n" +
	"\x17SessionSubmissionStatus\x12)\n" +
	"%SESSION_SUBMISSION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!SESSION_SUBMISSION_STATUS_PENDING\x10\x01\x12%\n" +
	"!SESSION_SUBMISSION_STATUS_CLAIMED\x10\x02\x12'\n" +
	"#SESSION_SUBMISSION_STATUS_COMMITTED\x10\x03\x12$\n" +
	" SESSION_SUBMISSION_STATUS_FAILED\x10\x04\x12)\n" +
	"%SESSION_SUBMISSION_STATUS_INTERRUPTED\x10\x05b\x06proto3"

var (
	file_proto_data_session_submission_proto_rawDescOnce sync.Once
	file_proto_data_session_submission_proto_rawDescData []byte
)

func file_proto_data_session_submission_proto_rawDescGZIP() []byte {
	file_proto_data_session_submission_proto_rawDescOnce.Do(func() {
		file_proto_data_session_submission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_session_submission_proto_rawDesc), len(file_proto_data_session_submission_proto_rawDesc)))
	})
	return file_proto_data_session_submission_proto_rawDescData
}

var file_proto_data_session_submission_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_data_session_submission_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_data_session_submission_proto_goTypes = []any{
	(SessionSubmissionStatus)(0), // 0: talon.data.SessionSubmissionStatus
	(*SessionSubmission)(nil),    // 1: talon.data.SessionSubmission
	(SessionExecutionPhase)(0),   // 2: talon.data.SessionExecutionPhase
}
var file_proto_data_session_submission_proto_depIdxs = []int32{
	0, // 0: talon.data.SessionSubmission.status:type_name -> talon.data.SessionSubmissionStatus
	2, // 1: talon.data.SessionSubmission.current_phase:type_name -> talon.data.SessionExecutionPhase
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_data_session_submission_proto_init() }
func file_proto_data_session_submission_proto_init() {
	if File_proto_data_session_submission_proto != nil {
		return
	}
	file_proto_data_session_journal_entry_proto_init()
	file_proto_data_session_submission_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_session_submission_proto_rawDesc), len(file_proto_data_session_submission_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_session_submission_proto_goTypes,
		DependencyIndexes: file_proto_data_session_submission_proto_depIdxs,
		EnumInfos:         file_proto_data_session_submission_proto_enumTypes,
		MessageInfos:      file_proto_data_session_submission_proto_msgTypes,
	}.Build()
	File_proto_data_session_submission_proto = out.File
	file_proto_data_session_submission_proto_goTypes = nil
	file_proto_data_session_submission_proto_depIdxs = nil
}
